### ISSUE TITLE
Can't seem to run the basic contributing commands?

### ISSUE THREAD

**Issue by delewis13** [getfider/fider#1005]
Mac Big Sur
Node 16.8.0
Docker 20.10.7
go 1.17 darwin/amd64
GNU make 3.81

Ran through all instructions as per `CONTRIBUTING.md`, running `make watch` gives:
```
make -j4 watch-server watch-ui
godotenv -f .env ./fider migrate
make[1]: godotenv: No such file or directory
npx webpack-cli -w
make[1]: *** [migrate] Error 1
make[1]: *** Waiting for unfinished jobs....
Webpack Bundle Analyzer saved stats file to /Users/daniellewis/Documents/fider/dist/assets.json
assets by path js/*.js 2.06 MiB 31 assets
assets by path css/*.css 85.2 KiB 18 assets
asset icons/sprite.f1f5bcc1c1e72d5e76d69f1491c8620d.svg 16.5 KiB [compared for emit]
webpack 5.52.0 compiled successfully in 7425 ms
No issues found
```

Where i believe `make[1]: godotenv: No such file or directory` is causing issues. Can't access app @ `localhost:3000`

Cheers!

**Comment by goenning** [comment]
Seems like you don’t godoenv installer or it’s not in your $PATH

try the instructions here https://github.com/joho/godotenv

Otherwise confirm that /usr/local/go/bin is in your $PATH

**Comment by goenning** [comment]
I just had to setup a new laptop and had the same issue.
It seems like go is installing all binaries into `~/go/bin` by default, so add that to your PATH env variable and it'll work.
