### ISSUE TITLE
[BUG] Stuck in activation email using gmail SMTP

### ISSUE THREAD

**Issue by thejess90** [getfider/fider#1013]
Fider Cloud or Self Hosted
Self Hosted - Heroku

Describe the bug
After Heroku deployed , 'Page not found' after filling up info for activation email. 

To Reproduce
Clean install to Heroku ,set with gmail SMTP (see my email setup below) and click on activation link in email.

Expected behaviour
Screenshots
https://fider88.herokuapp.com/

My email setup: (let me know if they are wrong)
![Untitled](https://user-images.githubusercontent.com/82879378/135214972-485956cb-0573-4685-852b-478624ea7062.png)

**Comment by thejess90** [comment]
I have edit my gmail setting here:
![Untitled](https://user-images.githubusercontent.com/82879378/135226097-3a2112a2-8cfa-4411-a6d3-7a377d12cd5a.png)


Encountered the following error: 
![222](https://user-images.githubusercontent.com/82879378/135226182-09397dad-813d-4724-bdf4-377caad968fd.JPG)

**Comment by goenning** [comment]
You need to use a SMTP service for transactional emails, gmail has a lot of built-in protection to avoid it being used in a scenario like this. I recommend using another service.
