### ISSUE TITLE
Building with lingui : missing exclusion ? 

### ISSUE THREAD

**Issue by esgn** [getfider/fider#1016]
Hi,

Just a quick remark regarding the build of fider. With running docker containers, `make build` halts on `Error: EACCES: permission denied, scandir '/home/myuser/mydir/fider/data/postgres'`

I think the issue could be avoided by adding an exclude rule to lingui configuration in `package.json`
```
"lingui": {
    "catalogs": [
      {
        "path": "<rootDir>/locale/{locale}/client",
        "include": [
          "<rootDir>"
        ],
        "exclude": ["**/data/postgres/**"]
      }
    ]
```

**Comment by esgn** [comment]
More broadly, is there a need for docker volumes in docker-compose.yml to be mapped to local folders instead of using named volumes ? I usually work with named volumes and `docker-compose down -v` for development.

**Comment by goenning** [comment]
Strange that I don’t have this issue you mentioned above. Maybe your using a different OS? I’m on a Mac

I’m not familiar with names volumes, how does that work?

**Comment by goenning** [comment]
Thanks all, I migrated the docker-compose to docker volumes so I guess this should no longer be a problem.
