### ISSUE TITLE
Limit post description length in webhooks

### ISSUE THREAD

**Issue by RuscalWorld** [getfider/fider#1026]
I'm using webhooks in Fider to publish all posts to Discord using its webhook system. The message in Discord can't be longer than 4000 symbols, but Fider doesn't have such limitation for post description. So, because of some users that create really big posts, some messages are not delivered to Discord webhook.

I think, there should be some property with short post description, so it can be passed to services that have limits on the message length. Maybe it will be better to provide an ability to reduce the post description to a certain length with template function like this:

```
{
	// ... some stuff
	"content": {{ shorten .post_description 4000 | quote }}
	// ... another stuff
}
```

```golang
"shorten": func(input string, length int) string {
	if len([]rune(input)) > length {
		input = string([]rune(input)[:length]) + "..."
	}
	return input
},
```

**Comment by goenning** [comment]
Yeah, that sounds like a good approach. Do you want to submit a PR?

I would just suggest calling it "truncate"

**Comment by RuscalWorld** [comment]
> Do you want to submit a PR?
Yes, sure. I will do this in the coming days
