### ISSUE TITLE
Replace BlackFriday with gomarkdown/markdown

### ISSUE THREAD

**Issue by elibroftw** [getfider/fider#1036]
Blackfriday is clearly no longer maintained. There are 100+ issues backlogged and 25 open pull requests dating back 5 years!

https://github.com/gomarkdown/markdown is a better markdown processor that is also maintained.

**Comment by goenning** [comment]
Yeah, that'd be great. I never really liked how inactive blackfriday repo was, but didn't find a suitable replacement at that time.

Would you like to submit a PR?
