### ISSUE TITLE
[BUG] SMTP connection is not working - Azure Deployment

### ISSUE THREAD

**Issue by dzak83** [getfider/fider#1038]
Hi,
I followed the "[Deploy on Azure](https://getfider.com/docs/hosting-on-azure)" tutorial to host my own version of fider. I got that part working and I see the page. My last step is to get an email from the system after initial sign in which is not working.

I verified that my noreply@{domain}.com email address works. I connected it to the local Outlook account with settings:
Outgoing port is 26
Incoming port is 110
SSL is NOT enabled
SMTP server is mail.{domain}.com

I can send and receive emails.

In the Azure settings, I have these:
![image](https://user-images.githubusercontent.com/27939815/146256897-bd444af2-d9e5-4bcc-b199-5df0fafe7e29.png)

where,
EMAIL_NOREPLY -> noreply@{domain}.com
EMAIL_SMTP_HOST -> mail.{domain}.com
EMAIL_SMTP_PASSWORD -> account password
EMAIL_SMTP_PORT -> 26  (same as I used in Outlook setup)
EMAIL_SMTP_USERNAME -> noreply@{domain}.com

What do I miss? 

How can I debug the email sending logic? I don't see anything in the application logs, I don't know what's failing and why.

**Comment by goenning** [comment]
I think it’s the same issue as GMail, please try another solution like Mailgun, AWS SES or SendGrid

gmail (and maybe outlook as well) doesn’t accept transactional email from apps.
