### ISSUE TITLE
[BUG] Gettting Page Not Found · Fider after following deploy on heroku docs

### ISSUE THREAD

**Issue by adriangzz** [getfider/fider#1044]
**Fider Cloud or Self Hosted**
Self hosted: 0.19.1

**Describe the bug**
After following the docs on self hosted with heroku, I get a blank page with "Page Not Found · Fider" as the <head> title. The build log showed the build succeeded. 

**To Reproduce**
1. Follow the [docs](https://getfider.com/docs/hosting-on-heroku) to self host in heroku.
2. Use custom smpt server (I used sendgrid)

**Expected behavior**
The website to load

**Comment by goenning** [comment]
Do you see anything on the logs?
Have you seen this https://github.com/getfider/fider/issues/1007?

**Comment by adriangzz** [comment]
That solved it, thanks @goenning! I think `HOST_DOMAIN: {APPNAME}.herokuapp.com` in the [docs](https://getfider.com/docs/hosting-on-heroku) is a little confusing, I thought since it had no explanation that it was the exact value to be set in the env vars.

Maybe changing it to `HOST_DOMAIN: <app_name>.herokuapp.com where app_name is the name you used to set up your Heroku app e.g. myapp.herokuapp.com` would help.
