### ISSUE TITLE
fider doesnt send emails

### ISSUE THREAD

**Issue by johi18** [getfider/fider#1046]
Hey there,
i am trying to get fider (selfhosted, docker) running. 
Fider starts perfectly fine, even with SSL, but does not send any emails. 
There are no error messages in the fider logs.

I have tried the SMTP and the mailgun variant, both does not work for me. 
There are also no entries in the email_verifications table.
I also tried different versions of fider and with and without SSL. 
The email settings are valid.

Here is my compose- file:
`version: '2'
services:
  db:
    restart: always
    image: postgres:12
    volumes:
      - /var/fider/pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: fider
      POSTGRES_PASSWORD: <pw>
  app:
    restart: always
    image: getfider/fider:main
    ports:
      - "3000:3000"
    environment:
      # Public Host Name
      HOST_DOMAIN: <mydomain>
      # Connection string to the PostgreSQL database
      DATABASE_URL: postgres://fider:<pw>@db:5432/fider?sslmode=disable

      # Generate a 512-bit secret here https://www.allkeysgenerator.com/Random/Security-Encryption-Key-Generator.aspx
      JWT_SECRET:<pw>

      # From which account e-mails will be sent
      EMAIL_NOREPLY: email@domain.dev

      ###
      # EMAIL
      # Either EMAIL_MAILGUN_* or EMAIL_SMTP_* is required
      ###

      #EMAIL_MAILGUN_API: <key>
     # EMAIL_MAILGUN_DOMAIN: <somevaliddomain>
      EMAIL_SMTP_HOST: some.valid.domain
      EMAIL_SMTP_PORT: 587
      EMAIL_SMTP_USERNAME: : email@domain.dev
      EMAIL_SMTP_PASSWORD: <pw>
      EMAIL_SMTP_ENABLE_STARTTLS: 'true' `

Do you have an idea what i am doing wrong?

**Comment by goenning** [comment]
What’s the SMTP server you’re using? I’ve seen many problems with gmail, yandex, hotmail, etc.

those services heavily block transactional emails. Best option is to use a transactional email service like mailgun, sendgrid or AWS SES

**Comment by johi18** [comment]
I use my own one, which works fine... 
The weird thing is that not even a error message is shown in the log that something went wrong with sending that email...

**Comment by goenning** [comment]
maybe it's not returning an error? because all errors received from the SMTP server are logged

**Comment by johi18** [comment]
The weird thing is that there is not even a log entry in the logs of the SMTP server... So fider doesnt even send a mail to the SMTP Server... 
The SMTP is configured correctly, we are using it on a daily basis.

**Comment by goenning** [comment]
can you try changing the LOG_LEVEL to DEBUG and post the results? It might have something useful there.

**Comment by johi18** [comment]
The Problem was the AdBlocker ,which was interfering with the JavaScript of fider. This is a Bug and it reproduceable. 
Adblock version 4.43.0 .

**Comment by goenning** [comment]
hey @johi18 thanks for the update, do you have any error log or information of what URL gets blocked by AdBlock?

**Comment by johi18** [comment]
unfortunately, no. It doenst look like that Adblocker blocks a URL... 
![image](https://user-images.githubusercontent.com/58742318/158352284-8730c2ca-b0c7-4fcd-95fe-bff2c6aa3388.png)
But when i deactivate the plugin, fider works fine
