### ISSUE TITLE
[BUG] Fider unavailable after setup

### ISSUE THREAD

**Issue by asos-robbell** [getfider/fider#1051]
**Fider Cloud or Self Hosted**
Self-hosted, on Kubernetes using image `main`

**Describe the bug**
After completing the setup form (/signup), the Fider activation email is sent and received successfully, but the application begins to respond with 404s to all requests. The only way to stop this happening is to tear down the database and redeploy the application. This has already been raised in #987 but that bug was closed without explanation.

**To Reproduce**
1. After deployment, go to the homepage and fill in the setup form
2. The email is sent successfully (and received), but all requests to Fider (both the activation link and the homepage) return a 404
3. Restarting the application shows that the database connection is still functioning (it can see that all migration steps have been run), but the app continues to respond with 404s

**Expected behavior**
The app responds with 200s

**Screenshots**

Logs before and after setup:
![image](https://user-images.githubusercontent.com/62598928/152571934-ebea66b9-3658-4000-9279-3caca3f9e98e.png)

Logs after restart:
![image](https://user-images.githubusercontent.com/62598928/152572042-d0e9f6d1-8156-47c3-a153-b63ab833a885.png)

**Comment by goenning** [comment]
1. do you know why it's showing IP addresses in some requests and the hostname in the POST? I'd take a guess here that your Ingress controller is not settings the Host header when forwarding the request. But i't funny how the POST request is showing the hostname.
2. can you try DEBUG to see if there's any other useful info?

**Comment by rafaelbantu** [comment]
I had this problem and only solved it after setting a URL. With IP did not work.

**Comment by asos-robbell** [comment]
So this looks like it was caused by a combination of things. HOST_DOMAIN wasn't set correctly, which I think could have contributed to requests being displayed as IP addresses. After setting that, the healthcheck I'd added began to fail because I haven't set up DNS (using a hosts entry on my machine for now), so callbacks were failing. Once I've got DNS set up I will confirm that all is working.
