### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by asmbu** [getfider/fider#1059]
**Fider Cloud or Self Hosted**
Hosted in azure with image getfider/fider:main

**Describe the bug**
Not all users receive email notifications even tough it is enabled in settings and they have subscribed to a post.

Fider is set up using plain SMTP with mailgun. Mailgun logs shows that there is only two users that receives email notification triggered by an event like post comment etc. I have tried sending email to users who do not receive notification using [mailgun API](https://documentation.mailgun.com/en/latest/quickstart-sending.html#send-with-smtp-or-api) and it worked just fine. 

Fider user settings and role is the same for those who receive email notification and those who do not.

**To Reproduce**
1. Go to a post
2. Post a comment
3. Check mailgun logs
4. See that not all recepients can be found in the logs

**Expected behavior**
I expect everyone that have email notification turn on and have subscribed to a post will receive an email notification.

**Screenshots**

**Additional context**
I have also tried:
- Turning off and on notification settings
- Unsubscribing to a post, then subscribe again
- Chrome and Microsoft Edge browser in incognitio window

Web notification is working fine. Also all invited email addresses receive an email.

**Comment by goenning** [comment]
Hey, I can't reproduce this issue. Do you have any public instance where I can login with 2 distinct accounts and have a look?

**Comment by asmbu** [comment]
Hello @goenning, I would rather not give you access because of confidentiality reasons. Now I have tried to deploy a new instance of fider with [azure](https://fider.io/docs/hosting-on-azure) and [docker](https://fider.io/docs/hosting-instance) and I am not able to reproduce the issue in a new fider instance. I suspect there is something wrong with database data because in the log I can see that _Notify about new comment_ is triggered. Unfortunately I cannot see which users will be notified from the console window.

![Notify about new comment](https://user-images.githubusercontent.com/74664420/158599966-3f8d5f69-02ae-4662-8b2a-a61344f63e2f.png)

A couple of additional questions:

- Can migrating a database from an old to a new version of fider cause any issues?
- Also, in my current fider instance, when I create a new post, all users are subscribed by default. I have not found any settings to change default notification settings. Have any of the previously fider versions notification settings enabled by default? These settings is not enabled by default in a new instance.

**Comment by asmbu** [comment]
In the users table in the database, there was a record were the email field was empty. Filling it with an email address solved the notification issue.
