### ISSUE TITLE
[BUG - Email not received]

### ISSUE THREAD

**Issue by dhspapa** [getfider/fider#1060]
**Fider Cloud or Self Hosted**
Host -> Heroku

**Describe the bug**
The installation procedure has been done, i can preview the Fider page but when i submit the starting form and the notification window for activating the account via email pops up I can't find the email sent by Fider(if sent). I have tried both custom domain(ex. example@mydomain.gr) and gmail(ex. example@gmail.com). I tried to pass the email_verification key from the database and it seems to work but that's not the purpose, it does not work properly. Is there any way to fix this issue?

1) Custom Email Configuration
HOST_DOMAIN  = example.herokuapp.com
JWT_SECRET = my_secret_key
EMAIL_NOREPLY = noreply@mydomain.gr
EMAIL_SMTP_HOST = mail.mydomain.gr
EMAIL_SMTP_PORT = 587 (also tried 465)
EMAIL_SMTP_USERNAME = example@mydomain.gr
EMAIL_SMTP_PASSWORD = my_email_password

-------------------------------------------------------------------

2) Gmail Configuration
HOST_DOMAIN  = example.herokuapp.com
JWT_SECRET = my_secret_key
EMAIL_NOREPLY = noreply@gmail.com - noreply@mydomain.gr
EMAIL_SMTP_HOST = smtp.gmail.com
EMAIL_SMTP_PORT = 587 (also tried 465)
EMAIL_SMTP_USERNAME = example@gmail.com
EMAIL_SMTP_PASSWORD = my_email_password

I also tried AWS SES but that didn't work either.

**Expected behavior**
Receive emails

**Screenshots**
![image](https://user-images.githubusercontent.com/39243346/158151861-70181a0d-15a4-4b4c-b057-1fd3fc929678.png)

**Comment by goenning** [comment]
Gmail doesn't like transaction email and they silently block these emails, there is no way around as far as i'm aware.

AWS SES works fine. Is your AWS SES enabled for production usage?

**Comment by dhspapa** [comment]
I've been trying for days to resolve it but nothing happens. 
AWS SES is enabled yes.

**Comment by dhspapa** [comment]
Is there any other opensource mailing service I can use?

**Comment by goenning** [comment]
Mailgun, SendGrid and any other that uses SMTP. I'm going to close this one as it seems to be a misconfiguration instead of bug.

**Comment by regardtnel** [comment]
Google recently changed their SMTP sending service.  Will have the same effect.  You need to be a Workspace user in order to make use of the SMTP sending service -> https://support.google.com/accounts/answer/6010255?hl=en
