### ISSUE TITLE
Cannot connect to DB?

### ISSUE THREAD

**Issue by eevleevs** [getfider/fider#1061]
Running on Kubernetes with 

```
DATABASE_URL = postgres://fider:$(POSTGRES_PASSWORD)@postgres:5432/fider?sslmode=disable
```

`POSTGRES_PASSWORD` from secret, confirmed correct (pgweb connects with the same string).

Giving the following and crashing:

```
INFO [2022-03-17T03:46:06Z] [MIGRATE] Running migrations...
INFO [2022-03-17T03:46:06Z] [MIGRATE] Found total of 70 migration files.
ERROR [2022-03-17T03:46:06Z] [MIGRATE] Error Trace:
- failed to get last migration record (app/pkg/dbx/migrate.go:58)
- pq: password authentication failed for user "fider"
```

Worked until redeployed today, no change to the configuration.

**Comment by goenning** [comment]
Hi, there is nothing new related to database connection in Fider, so that's likely to be something in your setup.

**Comment by eevleevs** [comment]
What could *something* be? Postgres runs in another container in the same namespace, and other pods in the namespace can connect to it without problems.

**Comment by goenning** [comment]
Based on the error message it seems like the password is wrong

**Comment by eevleevs** [comment]
Turned out that something strange happened with the pod config. Reading from the secret moved to the bottom of the env variables, so the password was not available to interpolate. Not related to fider after all.
