### ISSUE TITLE
Problem fider Behind Application Load Balancer

### ISSUE THREAD

**Issue by jnarvaezp** [getfider/fider#1065]
Hi Team.

I am currently trying to implement Fider behind an Application Load Balancer, but I have a problem when I place the service associated to a Target Group the application shows me the following error when it tries to do the health check

Requested hostname '192.168.2.10' does not match environment HOST_DOMAIN 'fedback.gururea.me'.

I understand that the Healthcheck process to fider only responds if the FQDN associated to the app is used, but in this case the Target Group only checks the IP http://192.168.2.10:3000/_health but when I consult this URL it returns 404, is it possible to configure the application to resolve fider or the healthcheck from the IP, that the FQDN is not mandatory when doing the healthcheck?

Thanks

**Comment by goenning** [comment]
hey @jnarvaezp can you have a look at this PR #1069

If you're still having this issue, please try using `getfider/fider:PR_1069` this version of the image contains this change.

**Comment by goenning** [comment]
I'm going to close this one as the latest version greatly simplify this by using relative path to resources. Just remember to set `BASE_URL` to `https://fedback.gururea.me` and remove `HOST_DOMAIN`.

Reopen if the problem persist even after updating to `getfider/fider:main`
