### ISSUE TITLE
[BUG] Callback URL is missing its scheme

### ISSUE THREAD

**Issue by asos-robbell** [getfider/fider#1074]
**Fider Cloud or Self Hosted**
v0.21.0

**Describe the bug**
When an Azure AD OAuth provider has been configured, the callback URL that is visible in the Authentication section doesn't appear to include the scheme (https://). This causes issues when Azure AD attempts to complete the callback: 

`AADSTS90102: 'redirect_uri' value must be a valid absolute URI.`

Note that the Azure portal will not allow the addition of a redirect URL that doesn't include a scheme. 

This issue was not present In version v0.20.0, where the scheme is visible in the list of enabled OAuth Providers.

**To Reproduce**
1. Create an Azure AD OAuth provider as per your instructions
2. Visit the Authenication section and observe that the Callback URL doesn't include the scheme
3. Test the OAuth provider to see the message from Azure AD, above

**Expected behavior**
Fider to include the scheme in the list of enabled OAuth providers and to pass on to the OAuth provider for callback to Fider. 

**Screenshots**
![image](https://user-images.githubusercontent.com/62598928/170097459-1774ddcc-e7b2-4f03-9211-8f0e2a79d216.png)

**Comment by goenning** [comment]
Does your BASE_URL starts with http://?

**Comment by asos-robbell** [comment]
Doing a little digging, this looks as though it may have been introduced by the move from HOST_DOMAIN to BASE_URL. Should BASE_URL be prefixed with the scheme?

**Comment by asos-robbell** [comment]
> Does your BASE_URL starts with http://?

No—we saw the log message after upgrading that HOST_DOMAIN had been replaced by BASE_URL, but previously HOST_DOMAIN didn't include the prefix. Just redeploying now with the scheme included.

**Comment by goenning** [comment]
@asos-robbell did it work?

**Comment by asos-robbell** [comment]
It did. Do you normally publish migration details for moving between versions?

**Comment by goenning** [comment]
I'm using the GitHub releases to communicate breaking changes. Although I missed the part that BASE_URL should be a valid URL, we could probably add a validation on start up as well.
