### ISSUE TITLE
[BUG] Sign-In with Discord no longer works in v0.210

### ISSUE THREAD

**Issue by majora2007** [getfider/fider#1076]
**Fider Cloud or Self Hosted**
Self Hosted, version v0.21.0

**Describe the bug**
Users are unable to login via "Discord Sign-In".  Error is:
```
{"redirect_uri": ["Not a well formed URL."]}
```
Url: 
https://discord.com/api/oauth2/authorize?client_id=910289229442088980&redirect_uri=feats.kavitareader.com%2Foauth%2F_ysk0qvb9xc%2Fcallback&response_type=code&scope=identify+email&state=https%3A%2F%2Ffeats.kavitareader.com%2F%7C5J5OfvHurHiuq0pIOYuVqNxKsYIGHuWa48pdW2zx6GcHWKRY

**To Reproduce**
1. Click Log In
2. Click on 'Discord Sign-In'
3. See error

**Expected behavior**
Be able to complete the flow (worked in previous version)

**Screenshots**
![image](https://user-images.githubusercontent.com/735851/170270551-c374927e-9f89-4d1e-817d-8f96abd5f783.png)

**Additional context**
This regression was introduced in v0.21.0

**Comment by goenning** [comment]
Have a look at #1074 if that helps

**Comment by majora2007** [comment]
Took a look, we've already migrated to BASE_URL and do not have https:// prefix. 

I will note, that the email flow to register does not send any confirmation mail either, not sure if that's related or not.

**Comment by goenning** [comment]
does it work if you add `https://`?

**Comment by majora2007** [comment]
Indeed it does. Thanks.
