### ISSUE TITLE
[BUG] AADSTS90102: redirect_uri value must be a valid absolute URI

### ISSUE THREAD

**Issue by asmbu** [getfider/fider#1082]
**Fider Cloud or Self Hosted**
`getfider/fider:0.21.0` hosted in azure App Service

**Describe the bug**
Use Docker image `getfider/fider:0.21.0` and replace environment variable `HOST_DOMAIN` to `BASE_URL`. Now it is no longer possible to sign in. I get the error `AADSTS90102: redirect_uri value must be a valid absolute URI`. 

**To Reproduce**
1. Open fider app
2. Click on 'sign in'
3. Type username and password

**Expected behavior**
Succesfully login to see the dashboard/posts.

**Screenshots**
![Fider sign in error](https://user-images.githubusercontent.com/74664420/173314819-2628d283-82ea-4bdb-83c6-a525922c357d.png)

**Additional context**
![fider whats changed](https://user-images.githubusercontent.com/74664420/173315090-d2c40e7b-e93b-433e-a111-d7899adc5e4a.png)

It only says to replace `HOST_DOMAIN` by `BASE_URL`. Is there any other environment variables that needs to be changed?

**Comment by goenning** [comment]
The BASE_URL must be a valid URL, you’re probably missing the scheme `https://`, for more info https://github.com/getfider/fider/issues/1074

**Comment by asmbu** [comment]
Yeah that's it, thank you
