### ISSUE TITLE
[BUG] Webhooks URLs for images aren't absolute since v0.21.0

### ISSUE THREAD

**Issue by jorys-paulin** [getfider/fider#1083]
**Fider Cloud or Self Hosted**
Fider self-hosted, version 0.21.0

**Describe the bug**
With the update to v0.21.0, `BASE_DOMAIN` was removed for single sites but it seems to be used for webhook templates, as such values that looked like `https://yourapp.fider.io/static/avatars/letter/1/Test` in v0.20.0 now looks like `/static/avatars/letter/1/Test`, so what was before an absolute URL is now a relative one and doesn't include the site's base url.

This causes issues with targets that expect an absolute URL, like Discord for example (that's how I discovered the problem, they refuse anything that doesn't begin with `https://`), as Fider sends an URL the target cannot understand.

**To Reproduce**
1. Go to webhooks
2. Create or edit a webhook
3. Click on the "more info" icon next to content
4. Note down the value of `author_avatar`, it doesn't include the site's base url
Try those steps again but in `v0.20.0` and prior, this this it includes the site's base url

**Expected behavior**
Variables such as `avatar_url` should be an absolute URL like `https://yourapp.fider.io/static/avatars/letter/1/Test` and not a relative one like `/static/avatars/letter/1/Test`, like it was before `v0.21.0` and how it's defined in the [documentation](https://fider.io/docs/using-webhooks)

**Screenshots**
![chrome_2022-07-03_15-46-50](https://user-images.githubusercontent.com/5084309/177042665-1acfb73e-f700-462e-b92a-f059d65ca7ca.png)

**Additional context**
This issue doesn't happen when running Fider in "multi" host mode, since the `HOST_DOMAIN` variable is defined

**Comment by goenning** [comment]
Do you have the BASE_URL env variable defined?

There were some changes around URL in 0.21, but it shouldn't have impacted this.

**Comment by jorys-paulin** [comment]
Yes, for our site in production it's set as `https://ideas.moonlight-stream.org` and on my dev machine it's set as `http://feedback.localhost`.
I've commented out the old `HOST_DOMAIN` since Fider wouldn't start with it defined, however it seems that same variable is used to make absolute URLs...

**Comment by jorys-paulin** [comment]
Small note, it seems like the meta tag for open graph is also using relative URLs, don't know if it was already the case though, but just to let you know

**Comment by goenning** [comment]
Thanks for all the inputs. Can you try using `getfider/fider:main` image once the last commit is deployed to DockerHub? It should force both OG images and WebHook urls to absolute urls.

**Comment by jorys-paulin** [comment]
Hello! Tried the newest commit on my dev machine and it works now!

**Comment by goenning** [comment]
Thanks! The `stable` docker image has this fix now.
