### ISSUE TITLE
SMTP - Unencrypted connection

### ISSUE THREAD

**Issue by smi-ed** [getfider/fider#1087]
## Expected Behavior

Sending emails via SMTP

## Current Behavior

Container logs:
- github.com/getfider/fider/app/services/email/smtp.sendMail:105 (app/pkg/errors/errors.go:39)
- failed to send email with template invite_email (app/services/email/smtp/smtp.go:105)
- unencrypted connection

## Possible Solution

Allows insecure and self-signed SSL certificates on SMTP server

## Steps to Reproduce

1. 
```
docker run -d --name=Fider --restart=unless-stopped \
  -p 3000:3000 \
  --volume /Docker/Fider/SSL:/app/etc \
  -e GO_ENV=production \
  -e BASE_URL=https://feedback.site.com \
  -e DATABASE_URL=postgres://databaseuser:databasepassword@ip/databasename?sslmode=disable \
  -e JWT_SECRET=secret \
  -e EMAIL_SMTP_ENABLE_STARTTLS=false \
  -e EMAIL_NOREPLY=noreply@site.com \
  -e EMAIL_SMTP_HOST=mail.site.com \
  -e EMAIL_SMTP_PORT=587 \
  -e EMAIL_SMTP_USERNAME=noreply@site.com \
  -e EMAIL_SMTP_PASSWORD=password \
  getfider/fider:main
```
2.

**Invitations** -> **Sample Invite** -> **Send a sample email to admin@site.com**

**Comment by goenning** [comment]
This should be fixed on the `main` branch now, but I can't validate it with my setup. If you're still using it, please give it a go.
