### ISSUE TITLE
[BUG] Access to S3 without access and secret access key

### ISSUE THREAD

**Issue by vitalvas** [getfider/fider#1096]
**Fider Cloud or Self Hosted**
self-hosted v0.21.1

**Describe the bug**
Applications will not start or panic on get data without Access Key ID and Secret Access Key.

**To Reproduce**
1. Create IAM role with full access to S3 bucket
2. Assing role to container
3. Start container

**Screenshots**
![image](https://user-images.githubusercontent.com/571747/195644160-d2b76b9b-6faa-42fd-bf9f-edf867974cc9.png)

**Comment by goenning** [comment]
That's not supported, but I'm happy to merge a PR if you'd like to contribute with this feature
