### ISSUE TITLE
[BUG] Timeout after starting container with Docker in local machine

### ISSUE THREAD

**Issue by Yolto7** [getfider/fider#1097]
**Fider Cloud or Self Hosted**
![Sin título](https://user-images.githubusercontent.com/87046922/195963544-fe9c57c5-bec2-434e-8cd9-a7ea1f54e0ea.png)
I have a problem, everything rises correctly with docker-compose, at the end when I see the logs I get:
![image](https://user-images.githubusercontent.com/87046922/195964138-33491ad4-8e1a-4597-a17d-5a3100f237bc.png)
but when I go to the link http://188.166.41.145, that it indicates in the documentation, it stays loading and nothing comes out. I already tried to place http://188.166.41.145:3000 and nothing either.

**Comment by Yolto7** [comment]
![image](https://user-images.githubusercontent.com/87046922/196300106-6e4f2b3b-bb7a-4724-b522-37ebf99a6f4b.png)
This is result when i try enter to http://188.166.41.145/

**Comment by peter-dough** [comment]
What was the solution/outcome of this issue? I am running into a similar scenario where I have the port defined.
