### ISSUE TITLE
Owasp: scanned webapplication

### ISSUE THREAD

**Issue by pharindoko** [getfider/fider#1113]
Hey,

I scanned the self-hosted fider instance using zap full scan (https://www.zaproxy.org/docs/docker/full-scan/) and found some issues. Please have a look to it.

docker image used:
getfider/fider:stable

**Comment by goenning** [comment]
Hey Florian,

Could you share the results to my email? I'm struggling to run this tool. contact@fider.io

Thanks 😊

**Comment by pharindoko** [comment]
Best option is to use docker ... 

docker run -t owasp/zap2docker-stable zap-full-scan.py -t https://{your-domain}

**Comment by goenning** [comment]
I tried that, but it kept running forever with no output at all 😟

I suspect it might be because I'm on an ARM laptop and the image might not support it properly

**Comment by pharindoko** [comment]
Yes seems like the docker image is not available for arm architecture yet ...
