### ISSUE TITLE
failed to get last migration record

### ISSUE THREAD

**Issue by shazadanjum2** [getfider/fider#1115]
Hi, 
Im Deploy Fider using Docker but im receiving issue in migration

ERROR [2023-01-31T08:49:09Z] [MIGRATE] Error Trace: 
2023-01-31 13:49:09 fider-app-1  | - failed to get last migration record (app/pkg/dbx/migrate.go:58)
2023-01-31 13:49:09 fider-app-1  | - dial tcp 127.0.0.1:32769: connect: connection refused

here is my **docker-compose.yml**

`version: '2'
services:
  db:
    restart: always
    image: postgres:15
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres-5WhG
      POSTGRES_PASSWORD: postgrespw
  app:
    restart: always
    image: getfider/fider:stable
    ports:
      - "80:3000"
    environment:
      # Public Host Name
      BASE_URL: https://feedback.taknik.com

      # Connection string to the PostgreSQL database
      DATABASE_URL: postgres://postgres:postgrespw@localhost:32769

      # Generate a 512-bit secret here https://www.allkeysgenerator.com/Random/Security-Encryption-Key-Generator.aspx
      JWT_SECRET: hsjl]W;&ZcHxT&FK;s%bgIQF:#ch=~#Al4:5]N;7V<qPZ3e9lT4'%;go;LIkc%k

      # From which account e-mails will be sent
      EMAIL_NOREPLY: noreply@taknik.com

      SSL_AUTO: "true"

      ###
      # EMAIL
      # Either EMAIL_MAILGUN_* or EMAIL_SMTP_* or EMAIL_AWSSES_* is required
      ###

      EMAIL_SMTP_HOST: smtp.taknik.com
      EMAIL_SMTP_PORT: 587
      EMAIL_SMTP_USERNAME: shahzad.anjum@taknik.com
      EMAIL_SMTP_PASSWORD: -----------------
      EMAIL_SMTP_ENABLE_STARTTLS: 'true'`

**Comment by goenning** [comment]
-> dial tcp 127.0.0.1:32769: connect: connection refused

review your settings, there is something off with the connection to your DB
