### ISSUE TITLE
hide sign in by email

### ISSUE THREAD

**Issue by smiledurepo** [getfider/fider#1122]
I don't want to let any person join in by any email
I want to be the only creator of users, not anyone should join

<img width="528" alt="imagen" src="https://user-images.githubusercontent.com/107485722/219949586-6a8e04ed-3229-4bd0-b114-a82cd91e154c.png">

**Comment by goenning** [comment]
Go to site settings -> Authentication. There is an option to disable that

**Comment by smiledurepo** [comment]
it's disabled

<img width="883" alt="imagen" src="https://user-images.githubusercontent.com/107485722/219952560-b14f7a19-9528-4c14-8f98-18dbb9d7fa84.png">


> Go to site settings -> Authentication. There is an option to disable that

**Comment by smiledurepo** [comment]
I enabled this and worked users get the email but when they click on the email link it shows Unauthorized message.
It would be cool if they don't get the email at all but that works.

<img width="578" alt="imagen" src="https://user-images.githubusercontent.com/107485722/219952788-580d56cb-0747-4632-9cc9-4f62e604eec7.png">
