### ISSUE TITLE
Request for New Release

### ISSUE THREAD

**Issue by Footur** [getfider/fider#1135]
It has come to our attention that Fider has not seen a new release for approximately one year, and we kindly request an updated release to address this concern. As active users of this software, we believe that a new release would greatly benefit the user community, enhance stability, and introduce important features and bug fixes.

**Comment by SmartPhoneLover** [comment]
+1

It's the only ticketing system that has the features I was searching on a open-source and selfhosted solution: simplicity, no extra tools (kanban board, email server, roadmap, etc, etc...), just a clear and simple to use ticketing system.

**Comment by DereckSimpatico** [comment]
+1

**Comment by mattwoberts** [comment]
We have a new release, and we're working on more features (driven of course from our own fider), thanks all for your patience!

**Comment by hhyyrylainen** [comment]
Great to hear!
When will the `stable` docker hub tag be updated? It's still the recommended tag for the image in your setup documentation.

**Comment by mattwoberts** [comment]
Yes pretty soon - just wanted to make sure all was well :)
