### ISSUE TITLE
Fider on Kubernetes

### ISSUE THREAD

**Issue by Footur** [getfider/fider#1138]
I am currently developing a Helm chart for Kubernetes and would like to request official support and maintenance for deploying Fider on Kubernetes using Helm. I believe that by providing this support, it would greatly benefit the Fider community and streamline the deployment process for Fider instances on Kubernetes.

As the creator of the Helm chart, I am committed to actively contributing to its development, testing, and bug fixes.

I hope it is okay that I did not create a feature request on feedback.fider.io.

**Comment by goenning** [comment]
Hey, thanks for your interest in contributing. I think having a helm chart would make deployment a lot easier for sure.

I just would like to avoid having it on this repo, maybe we could have a separate one and I can give you write access to it so you can maintain it. What you think?

**Comment by Footur** [comment]
Hey @goenning, sounds great. I am in!

**Comment by goenning** [comment]
Done!

**Comment by Footur** [comment]
The first helm chart is released! :tada: 

https://github.com/getfider/helm/releases
