### ISSUE TITLE
[BUG] SendGrid Not Sending Email

### ISSUE THREAD

**Issue by matheus-rodrigues00** [getfider/fider#1148]
**Fider Cloud or Self Hosted**
Self Hosted FIder, version 0.21.1

**Describe the bug**
We're not able to send e-mail confirmation with SendGrid.

**To Reproduce**
Just follow Docker installation from docs and setup STMP configuration for SendGrid. Here's the SMTP part:
```yml
EMAIL_NOREPLY: my@email.noreply
EMAIL_SMTP_HOST: smtp.sendgrid.net
EMAIL_SMTP_PORT: 587
EMAIL_SMTP_USERNAME: apiKey
EMAIL_SMTP_PASSWORD: SG.myApiKey
EMAIL_SMTP_ENABLE_STARTTLS: 'true'
```

**Expected behavior**
Should send confirmation e-mail to the provided email

**Comment by matheus-rodrigues00** [comment]
@goenning S.O.S.

**Comment by taiebnoe** [comment]
SOS

**Comment by matheus-rodrigues00** [comment]
@taiebnoe we only managed to use w/ Google SMTP.

**Comment by Iam1337** [comment]
Same here. **Docker, tag stable**. I use a custom email service. A self-hosted solution like Wiki.js sends mail normally, but Fider thinks for a long time and returns EOD.

Temporarily switched to tag main, where the current version is 202205082055. Sending mails worked.
