### ISSUE TITLE
[BUG] SMTP SSL does not work

### ISSUE THREAD

**Issue by realashleybailey** [getfider/fider#1150]
**Fider Cloud or Self Hosted**
latest

**Describe the bug**
SSL SMTP does not work even with `EMAIL_SMTP_ENABLE_STARTTLS` disabled and set to "false" (also tried `false`), using port 465 and mail.example.com (example.com in replacement of actual mail server), I can verify that both online SMTP test tools and other email clients can all properly work with my mail server.

**To Reproduce**
Send SMTP invite over SSL

**Expected behavior**
Email should send

**Comment by goenning** [comment]
nothing I can do here, issues with SMTP are often related to configuration
