### ISSUE TITLE
[BUG] ERR_HTTP2_PROTOCOL_ERROR on callback URL

### ISSUE THREAD

**Issue by shilpapoloj** [getfider/fider#1154]
**Fider Cloud or Self Hosted**
Self Hosted (latest image 'getfider/fider:stable')

**Describe the bug**
OAuth Provider with Azure is configured manually on the application. When testing the authentication, I can sign-in successfully but after few seconds Im seeing this error

```
might be temporarily down or it may have moved permanently to a new web address.
ERR_HTTP2_PROTOCOL_ERROR
```
I have contacted Microsoft Azure support and they have mentioned that application is not accepting the provided token

**To Reproduce**
Followed this doc https://fider.io/docs/configuring-oauth 

**Expected behavior**
redirected to Fider after successful authentication

**Comment by goenning** [comment]
seems like some misconfiguration on https/address on your Azure callback
