### ISSUE TITLE
[BUG] X cannot be used as a JSX component

### ISSUE THREAD

**Issue by Justman100** [getfider/fider#1161]
`NODE_ENV=production yarn webpack-cli`

> [log.txt](https://github.com/getfider/fider/files/14196077/log.txt)

**Comment by Justman100** [comment]
@goenning

**Comment by Justman100** [comment]
@goenning

**Comment by goenning** [comment]
seems like there was an update on that npm dependency, use the versions locked on package-lock.json

**Comment by Justman100** [comment]
> seems like there was an update on that npm dependency, use the versions locked on package-lock.json

Yeah, used Yarn, wich seemly installed newer versions! After using of NPM, it works!

**Comment by Justman100** [comment]
Oh, and! Never close Issues/PRs without discussion

**Comment by Justman100** [comment]
Oh, and... Never close Issues/PRs without discussion
