### ISSUE TITLE
Account is Pending Activation

### ISSUE THREAD

**Issue by DereckSimpatico** [getfider/fider#1162]
Hello,

We just finished setting up version 0.21.0 as the newest version has the signup bug. It looks like the activation email never gets sent or I am missing something.

Any thoughts on this would be greatly appreciated!

**Comment by Servery** [comment]
Is there any error in your logs?
`docker compose logs app`

**Comment by mattwoberts** [comment]
Indeed, look for error messages, if there is nothing there you could try blowing away the setup and starting with a clean postgres:

From https://fider.io/docs/hosting-instance:

...To solve this you'll need to log into your Postgres Database and run TRUNCATE TABLE tenants RESTART IDENTITY CASCADE;. This command will purge all the data from Fider, thus making the installation page available again. You may now change your email configurations and try again. You can repeat this as much as you need.

**Comment by mattwoberts** [comment]
Closing this one - looks like a good example of something that would be helped with #1204

**Comment by DanielSousa** [comment]
I've also faced some issues with email activation when setting on local env with docker. 
If anyone need to run the command like @mattwoberts mention, here it is:
`docker-compose exec db psql -U fider -d fider -c "TRUNCATE TABLE tenants RESTART IDENTITY CASCADE;"`
