### ISSUE TITLE
Is Fider still maintained?

### ISSUE THREAD

**Issue by mihha** [getfider/fider#1166]
Hi everyone!

I apologize for opening this issue, but I didn't know how else I can reach the developers

I just wonder if Fider is still maintained or is it a dead project now?

**Comment by mattwoberts** [comment]
Hey there.

So in summary - yes, at least it will be going forwards from now.

I'm taking over from @goenning for this project now, and we are planning lots of feature updates and general maintenance for fider. We're still going through the hand-over process and working things out, but it's definitely not dead. I'll get some new releases out soon with updated go / node versions as a start, and we'll start adding things and working through soon :)

**Comment by mihha** [comment]
Hi!

Thank you for taking the time to respond to my question

I am happy to hear that this project will continue to live

I wish you all the best in your effort

Regards,
Igor
