### ISSUE TITLE
Problem with self hosted user stuck in pending activation state

### ISSUE THREAD

**Issue by suityou01** [getfider/fider#1171]
I set up an instance of fider running on my k8s cluster. I hit the main page and completed sign up. I had not set up mailhog and found out that email is a vital part of new user setup. So I set up mailhog properly.

I now want to start again, from scratch. I removed the user from the email_verifications table and tried again. The front end is stuck on "YOUR ACCOUNT IS PENDING ACTIVATION".

I cleared all site data, tried another browser, an incognito window, nothing works. It is stuck on this whenever I hit the endpoint.

How can I reset this application state so it signs me up as a new user?

**Comment by mattwoberts** [comment]
There is a FAQ at the bottom of here - I think this should sort you out

https://fider.io/docs/hosting-instance

**Comment by vbresan** [comment]
@suityou01 Have you managed to resolve the issue? My SMTP settings were not correct, so the activation email was never sent. Now I am stuck at the same spot.

@mattwoberts I believe that when an error is detected while sending the confirmation email, the account should not enter the 'pending activation' state.

**Comment by mattwoberts** [comment]
Just checked this against a test docker instance, and all fine for me. 


![CleanShot 2024-07-11 at 15 18 38@2x](https://github.com/getfider/fider/assets/109196/f5323b50-2f4e-4cb2-a3cf-0a50f29c0259)

**Comment by vbresan** [comment]
@mattwoberts In that case, I believe that my problem is related to this [discussion](https://github.com/getfider/fider/discussions/1174).
