### ISSUE TITLE
Instructions for self-hosted deploy with docker are outdated

### ISSUE THREAD

**Issue by vbresan** [getfider/fider#1173]
Instructions are available [here](https://fider.io/docs/hosting-instance). In 'Installing and Running' section, `docker-compose.yml` file contains the following:

```
# Generate a 512-bit secret here https://www.allkeysgenerator.com/Random/Security-Encryption-Key-Generator.aspx
JWT_SECRET: VERY_STRONG_SECRET_SHOULD_BE_USED_HERE
```

https://www.allkeysgenerator.com is down since June 2023. I ended up using https://jwtsecret.com though I am not sure what would you recommend.

As well, once `docker compose pull` is run, the following message is displayed:
`WARN[0000] /var/fider/docker-compose.yml: "version" is obsolete`

Also, the following message shouldn't have a dash between `docker` and `compose`:

> You can find the logs by using `docker-compose logs app`. 

In my case, I also had to manually create database "fider", which is not mentioned in the documentation. See my related discussion [here](https://github.com/getfider/fider/discussions/1174).

**Comment by mattwoberts** [comment]
Cheers, I've taken this on board here

https://github.com/getfider/fider.io/pull/43
