### ISSUE TITLE
[BUG] Duplicate primary keys prevent creating db entries after restoring a backup

### ISSUE THREAD

**Issue by TadeSF** [getfider/fider#1210]
**Fider Cloud or Self Hosted**
Self Hosted v0.22.0

**Describe the bug**
After recovering from a backup, the ID-assining mechanism is not agnostic of the fact, that IDs might already be taken from restored database entries. Therefore, I had problems creating posts, comments, tags, users, notifications, etc. I had to try to click the post creation button about 30 times while getting errors until it finally counted high enough to find a free ID in the database and worked. Same with the other types – especially annoying with the notifications, since I had to create about 100 of them (i did it by spam commenting and deleting the post afterwards), until my slack notifications worked again.

**To Reproduce**
I started by creating a new Fider Instance, letting all migrations run and creating a new tennant.
Since my regular postgres backup failed (because I backed up the wrong database 🤦 ), I had no sql dump to restore (but I imagine the problem would still be present). Instead, I luckily had a manual backup taken from the Export Page `/admin/export` in form of a .zip with json files representing (almost) all entities. Because I couldn't find any instructions I used a [JSON to SQL Converter](https://www.convertjson.com/json-to-sql.htm) to mass produce me the `INSERT` statements and manually recreated the database.
After that, the problems were immediately present.

**Expected behavior**
A Duplicate ID should never be an issue while creating. The App should handle such errors in a way that a free ID is assigned on creation of a database entry.

**Screenshots**
This is a sample of one of the many (but always similar) psql errors:
```
INFO [2024-09-21T15:22:27Z] [BGW] Task 'Notify about new post' started on worker '2'
ERROR [2024-09-21T15:22:27Z] [BGW] Error Trace: 
- app/tasks/new_post.go:39
- failed to insert notification (app/services/sqlstore/postgres/notification.go:139)
- failed to execute trx.Get (app/pkg/dbx/dbx.go:319)
- pq: duplicate key value violates unique constraint "notifications_pkey"
```

**Additional context**
I tried to look up how the app assigns IDs, but I am not really good with GO... I would suggest changing the IDs to either look for the next free ID instead of failing if the assigned ID is already present (could be done with a try/catch around the database query) or assigning a random ID with a large number.
For the numbering of the posts (as far as I understood that is a different number from the ID), I would suggest just querying for the maximum number present in all posts and assigning the next higher number to the new post.

**Comment by mattwoberts** [comment]
Hi

Glad to hear that you managed to get your JSON data back into the db.

What happened is that since you inserted into the SERIAL fields, postgres was then out of sync, which caused your issues.

What you needed to do I think is in your script, ensure that you update the serial in postgres - something like 

```sql
SELECT setval('your_sequence_name', (SELECT MAX(your_column_name) FROM your_table_name) + 1);
```

**Comment by TadeSF** [comment]
Thanks so much! That seemed to have done the trick. Just out of curiosity – would that have been different when restoring from a postgres dump? It seems odd to me having to do the syncing manually...

Also, are you planning to integrate tooling that enables to restore the backup with the manual downloaded zip file?

**Comment by mattwoberts** [comment]
From a psql backup you wouldn't need to do this, this is just when you're generating sql insert statements to insert the data.

There are no plans at the moment to add tooling to restore from a previous manual backup - might be a good one to add to https://feedback.fider.io though!
