### ISSUE TITLE
Can You Update Chinese Version Quickly? Please!

### ISSUE THREAD

**Issue by XJY00** [getfider/fider#1223]
Can You Update Chinese Version Quickly? Please!
i also used https://github.com/astuto/astuto,
but i cant set astuto smtp
so, i have chiose, i want use better product

**Comment by mattwoberts** [comment]
Hey @XJY00 

Sorry, we're a tiny team here.

I've been working on this this weekend though - I've just pushed a new version with it, and as I type there should be a new stable docker image being created!

Matt
