### ISSUE TITLE
Incorrect example file in « hosting your own instance »

### ISSUE THREAD

**Issue by sapiens-sapide** [getfider/fider#137]
The documentation for env variables write : 
```
# GitHub
      # OAUTH_GITHUB_APPID: <github_client_id>
```
But the correct env variable to set is `OAUTH_GITHUB_CLIENTID`

*BTW*: it should be mentionned that callback url is : `http://your.server.tld/oauth/github/callback`
*BTW2*: the callback url should enforce the same http scheme (http or https).

**Comment by goenning** [comment]
Good catch! I'll update it.

Regarding *BTW2*: I'm not sure if I understood what you mean. Fider currently binds to either http OR https. So the URL you set as the callback in google/facebook/github must match with the whatever Fider is using. Is that what you mean?

**Comment by goenning** [comment]
Docs have been updated. Thanks!
