### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by lucasvdh** [getfider/fider#202]
I was wondering if you could create a basic API documentation.

I'd love to integrate Fider in our application but I'm not familiar with Go and don't have the time to go through the code to find out how I can build a client.

From the top of my head I'd say the minimum docs would need to provide the following:

- authorization description
- overview of all the endpoints
- request example for each endpoint
- response example for each endpoint (fail and succes).

I've had good experiences with [API Blueprint](https://apiblueprint.org/).

**Comment by goenning** [comment]
We actually don't even have a public API yet, so that needs to come first before the documentation. But I can totally see the value of having it. I'm just curious, which operations would you like to use?

**Comment by goenning** [comment]
Because this is a new feature request, I have moved it to Fider. Let's discuss it there, gather some more votes/suggestions and we'll see later what we can do.

Moved to: https://feedback.fider.io/ideas/55/provide-an-api-to-allow-integration-with-other-applications
