### ISSUE TITLE
Idea visibility attribute

### ISSUE THREAD

**Issue by lucasvdh** [getfider/fider#203]
Adding a visibility attribute to the Idea model so an idea can be made private. If the idea is private it is only seen by and can only be made public by admins/collaborators. If the value is not passed in the create call the default value would be public.

**Comment by goenning** [comment]
Because this is a new feature request, I have moved it to Fider. Let's discuss it there, gather some more votes/suggestions and we'll see later what we can do.

Moved to: https://feedback.fider.io/ideas/54/idea-visibility-attribute
