### ISSUE TITLE
Wrong base URL when hosted behind a TLS reverse proxy

### ISSUE THREAD

**Issue by Hellslicer** [getfider/fider#253]
https://github.com/getfider/fider/blob/master/app/pkg/web/context.go#L269
```golang
//BaseURL returns base URL as string
func (ctx *Context) BaseURL() string {
	protocol := "http"
	if ctx.Request.TLS != nil {
		protocol = "https"
	}
	return protocol + "://" + ctx.Request.Host
}
```

When hosted behind a TLS reverse proxy (without TLS between proxy and Fider), `Request.TLS` is `nil` and therefore it leads to:
- Mixed HTTP / HTTPS
- A blank page for the main page (`history.replaceState` will not work with a wrong URL).

A potential solution would be to set a new `BASE_URL` environment variable.

**Comment by goenning** [comment]
Hey @Hellslicer, thanks for the detailed bug report, that's very helpful.

I'd try to avoid adding more env variables if possible. AFAIK, most reverse proxy tools add a `X-Forwarded-Proto` that we could use. What you think? Does your proxy do it?

**Comment by Hellslicer** [comment]
Hi @goenning,
Indeed, we could use the standard `X-Forwarded-Proto` header. My reverse proxy correctly set it to `https`.
I'll make a small PR to add an `https` check from this header.

**Comment by michaelhofer** [comment]
I just found this because we had the same issue. Just in case that somebody has the same, adding the following to the NGINX config does help:

```
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Host $http_host;
```

**Comment by easaw** [comment]
I found that the base URL needs to be 'https://feedback.example.com' rather than just 'feedback.example.com' otherwise the front-end URLs end up being https://feedback.example.com/feedback.example.com/assets/whatever.js for example.
