### ISSUE TITLE
MySQL

### ISSUE THREAD

**Issue by b1f17773** [getfider/fider#264]
Hi
is there any chance to install fider without docker and on MySQL ?

**Comment by goenning** [comment]
Hey,

We don't distribute binaries yet, so you'd need to compile it yourself. It's somehow similar to this [CONTRIBUTING](https://github.com/getfider/fider/blob/master/CONTRIBUTING.md) guide. 

But there's no way to run it without PostgreSQL and we don't have plans to support other databases in short term.

**Comment by LukeSheard** [comment]
@goenning Any helpful advice if I wanted to convert the code to run on mysql? I started having a little look around but I'm still fairly new to golang.

**Comment by goenning** [comment]
@LukeSheard what I can think about right now is:

- add mysql driver (https://github.com/go-sql-driver/mysql/) 
- create a mysql package that implements all storage interface for mysql (https://github.com/getfider/fider/tree/master/app/storage)
- parse DATABASE_URL and choose between mysql or postgres implementation

Most queries that are written for postgres *SHOULD* work on MySQL, so copying all the postgres implementation and running unit tests against it will give you a good idea of which queries doesn't work on mysql.

**Comment by petrk94** [comment]
Any update?

**Comment by mdemierre** [comment]
> @LukeSheard what I can think about right now is:
> 
> * add mysql driver (https://github.com/go-sql-driver/mysql/)
> * create a mysql package that implements all storage interface for mysql (https://github.com/getfider/fider/tree/master/app/storage)
> * parse DATABASE_URL and choose between mysql or postgres implementation
> 
> Most queries that are written for postgres _SHOULD_ work on MySQL, so copying all the postgres implementation and running unit tests against it will give you a good idea of which queries doesn't work on mysql.

I tried those steps today and it's more work than it seems at first glance. At least the following would need to be adapted to work with MySQL/MariaDB:

- Migrations (especially column types such as `timestamptz` --> `datetime`). Here it's probably simpler to separate the two DBs and have only one initial migration for mysql. But later migrations will need to be implemented for both DBs.
- All prepared statements (`$1` syntax --> `?` syntax)
- There are differences in how dates  and timestamps are handled which might create some issues (if I understand correctly Fider is currently letting Postgres localize timestamps, MySQL can do that too but its TIMESTAMP columns suffer of the 2038 problem)
