### ISSUE TITLE
Better dynamic SQL queries management

### ISSUE THREAD

**Issue by goenning** [getfider/fider#284]
Problems:
- Dynamic queries are hard to write/read/maintain. See `postgres.PostStorage`
- Big SQL Queries are hard to reuse.

Solutions:
- Move big SQL queries to another file that is read on runtime?
- Use text/template to build queries?
- Create some kind of abstraction to help build queries on runtime?

**Comment by LukeSheard** [comment]
Seems like this would go really well with #268?

**Comment by goenning** [comment]
Yes, we could refactor it and make it easier to deal with multi database without having to duplicate all queries.
