### ISSUE TITLE
Implement security recommendations from mozilla.org

### ISSUE THREAD

**Issue by goenning** [getfider/fider#293]
https://observatory.mozilla.org and https://securityheaders.io/

Current Score 

Test | Score | Explanation
-- | -- | --
Content Security Policy |-25| Content Security Policy (CSP) header not implemented |  
HTTP Strict Transport Security |-20 | HTTP Strict Transport Security (HSTS) header not implemented |
 Referrer Policy | 0 | Referrer-Policy header not implemented (optional) |  
Subresource Integrity | -5 | Subresource Integrity (SRI) not implemented, but all external scripts are loaded over https |   
X-Content-Type-Options |-5 | X-Content-Type-Options header not implemented |  
X-Frame-Options | -20 | X-Frame-Options (XFO) header not implemented | 
X-XSS-Protection | -10 | X-XSS-Protection header not implemented  |

**Comment by goenning** [comment]
`HTTP Strict Transport Security` is the only setting we won't cover on this issue. The reason is  that it'll require some effort to make it work as opt-in, read more on https://hstspreload.org/#opt-in

We'll need to revisit this later.

**Comment by ry4nolson** [comment]
would you consider not setting `X-Frame-Options`?
This would let fider be used in a modal.

**Comment by goenning** [comment]
I thought a lot about that before setting it. Ideally we should have a site setting where you could input your frame host domain, so we would be able to use ALLOW-FROM <domain>

Did I break something on your side? Or are you just thinking about future possibilities? I’m fine with reverting that specific header until we can make it more flexible.
