### ISSUE TITLE
Cache Gravatar response

### ISSUE THREAD

**Issue by goenning** [getfider/fider#307]
**Problem:** Gravatar pictures are proxied through Fider to keep user’s emails private. Right now, every request to Fider Gravatar proxy will send a new request to Gravatar, which can add some overhead to the servers if there are many users online.

**Solution:** Gravatar imagens should be cached for a few hours/days in-memory at Fider server.

A `map[string][]byte` is a good candidate to cache the images.

**Comment by nylen** [comment]
@goenning: an alternative would be to have the browser request a Gravatar directly.  This is what all WP sites do, and it's [the expected use case](https://en.gravatar.com/site/implement/images/) for other implementations as well.  Would this be an acceptable solution?

**Comment by goenning** [comment]
We used to do that, but we got an interesting bug report that it’s easy to reverse engineer the md5 code and “steal” the email from users, which is a valid point!

Since then we’ve been using Fider as a proxy to Gravatar.

**Comment by cameronmoreau** [comment]
It looks like this issue has been open for a while so I'll go ahead and take a stab!
