### ISSUE TITLE
Custom domain can't use CNAME for "naked domain"

### ISSUE THREAD

**Issue by gagarine** [getfider/fider#345]
The documentation provided for bar domain is incorrect. You can use CNAME record for "naked domain".

![screen shot 2018-04-11 at 20 23 05](https://user-images.githubusercontent.com/164074/38635620-3a52fdfa-3dc6-11e8-92ac-6ea89e5a729d.png)

Actually I pinged fider.io and used the 174.138.111.44 IP. Waiting for the propagation to see if it works.

**Comment by gagarine** [comment]
Yes, but CNAME record are not allowed on naked domain. You can use a CNAME record for `sub.test.com` but not for `test.com`.
https://serverfault.com/questions/613829/why-cant-a-cname-record-be-used-at-the-apex-aka-root-of-a-domain

**Comment by goenning** [comment]
Thanks for sharing that, I wasn't aware of it. 

I recommended CNAME so that I could have freedom to change the IP whenever needed (although it never happened). But now that I understood the issue, I'll update the docs to mention that IP when CNAME is not possible, and keep the IP stable from on.
