### ISSUE TITLE
Show generic error toaster message when API call fails (status code 5xx)

### ISSUE THREAD

**Issue by goenning** [getfider/fider#426]
**Problem:** when calling the API via fetch function, we always expect that the server will respond with a status between 200 and 499. But if we get a 500 response for any reason, we’ll simply ignore for now, which is very bad.

**Solution:** We should hook up the API calls to the toaster service so that if any 500 response is returned, we show a generic error message mentioning that something went wrong. We’ll at least inform the user that the operation they performed failed.

**Comment by kelsier27** [comment]
I would like to work on this. Are there any specifications I need to keep in mind while developing this?

**Comment by kelsier27** [comment]
Is there a Slack/Gitter/IRC channel where I can talk to the Fider dev team. I want to ask a few doubts about the codebase and discuss my implementation for resolving this issue.

**Comment by goenning** [comment]
@kelsier27 We don't have a chat area. I'd like to keep the technical discussion within GitHub, at least for now that the community is small. You can drop us your questions here or open a PR with a [WIP] prefix and we can discuss it there. Whatever you prefer!
