### ISSUE TITLE
Fider is not compatible with Windows for development

### ISSUE THREAD

**Issue by goenning** [getfider/fider#434]
It is not yet possible to develop on Fider, first issue is that we're using Make that is not compatible with Windows.

There are some unit tests failing only on Windows, probably because of some platform specific things like CRLF.

If you're a Windows user and want to help us out, please do the changes required for the [CONTRIBUTING.md](https://github.com/getfider/fider/blob/master/CONTRIBUTING.md) guide to work  on Windows the same way it works on Linux/macOS.

**Comment by goenning** [comment]
Hey, thanks for your feedback. I totally agree with you. But I forgot to add the reason why I suggested the change.

I want Fider to be an inclusive project that anyone can contribute. As far as I know, using make on Windows is complicated. I don’t know if it has changed since I last used, but I’d like to use more cross-platform tools.

Aside from Make, we use Docker, NPM/Node and Go, which all work well on Windows.

**Comment by nylen** [comment]
I hear that Windows Subsystem for Linux has gotten pretty good lately.  Granted, I don't use Windows, and I don't know how much interest you have in this project from people who do.

**Comment by Mohammed90** [comment]
What about [Mage](https://magefile.org)? It's cross-platform, uses Go (which the project already uses), and you get the benefit of using full-fledged statically-typed programing language.

**Comment by goenning** [comment]
If Make works well on WSL, then we can close this issue. Anyone using Windows can try it out? Otherwise I’ll do once I’m back.

Mage looks good, although it’d be better if we can avoid additional dependencies. NPM solves this as it’s already a mandatory dependency, but has all the overhead issues mentioned above.

**Comment by goenning** [comment]
Ok, so as suggested by @Mohammed90, I've replace Make with Mage. It's working well on macOS and Windows, but that's not enough, more changes will be required as some unit tests are failing on Windows. I've add a comment on CONTRIBUTING.md if any Windows users wants to jump into this issue.

For future reference, if https://github.com/magefile/mage/issues/182 is resolved, we can change `air.conf` to be cross-platform by using:

```
[build]
bin = "mage run"
cmd = "mage build:server"
```

**Comment by takuy** [comment]
@goenning Is this still an issue? I saw in your last comment that mage allowed this to work on Windows. Whenever I try to run (after installing the requirements), mage watch just shows this as the very last thing and nothing else. Navigating to localhost:3000 just returns a connection refused error. The normal Docker container is able to run just fine though. 

```
!exclude dist
No type errors found
Version: typescript 3.3.3333
Time: 9483ms
```

Further up in the log, I get: 
``` 
operable program or batch file.b.com\getfider\fider\godotenv' is not recognized as an internal or external command, 
```
