### ISSUE TITLE
Embed Fider (Mobile and Web)

### ISSUE THREAD

**Issue by goenning** [getfider/fider#442]
Request: https://feedback.fider.io/ideas/105/embed-fider-into-website-or-mobile-app

Open questions: 
- how to authenticate with OAuth?
- force consumers to send auth token? (obtained from API)

### Web: iframes

Facebook/Google doesn't allow OAuth inside Iframe. Potential solution is to open popup, authenticate, close popup and refresh main frame/iframe. (only do this if inside iframe?!)

### Mobile: WebView

???

**Comment by peterver** [comment]
@goenning for the mobile, what about cordova or flutter ? 

https://flutter.io/ ( new, 1.0 was only recently released )
https://cordova.apache.org/ ( old but still very much alive and kicking )
