### ISSUE TITLE
remove unused uploads on startup

### ISSUE THREAD

**Issue by goenning** [getfider/fider#479]
**Problem:** Every time a user uploads a new Logo, Fider will create a new record on `uploads` table and update the `tenants` table field `logo_id` to the new `id` generated from the `uploads` table. Every new page will use the new logo instead of the previous one. The problem is that we now have old logos on the `uploads` table that are not used anymore.

**Solution:** The solution I can think about is to remove all orphaned `uploads` records on startup. We could also remove when we upload new logos, but that means we'd need to do apply this change to multiple places in our codebase, not to mention any other future file upload would also require this.

**Comment by midnightrun** [comment]
Hi Guilherme,
sounds like a job for me, if no one already is working on it :)

**Comment by goenning** [comment]
No one else said anything, so it’s yours! 😀 Have fun and let me know if you need something!

**Comment by goenning** [comment]
I don't see any error on that log. You also got a `http server started on :3000`, which means that Fider has successfully started.

But are you following [the installation guide](https://getfider.com/docs/hosting-instance/) or the [contributing guide](https://github.com/getfider/fider/blob/master/CONTRIBUTING.md#getting-started-with-fider-codebase)? Based on your logs, I'd say it's the installation guide. If your plan is to develop on Fider, you should be using the contributing guide.

**Comment by midnightrun** [comment]
Hi,
I just got it working. Will now take the time to add this feature :)

**Comment by peterver** [comment]
@goenning @midnightrun what about generating a single id for a user/setup and then just overriding the file itself ?

**Comment by goenning** [comment]
The main issue would be browser caching, we cache hard on user uploaded images. Having a new file name solves this issue.

But this whole topic might not be needed required anymore, because S3 (and also File System) is a possible backend to store user uploaded images (https://github.com/getfider/fider/issues/671). On S3/FS having orphan files is not a big deal.

**Comment by lcd1232** [comment]
Hi.
I can take if no one take it.
