### ISSUE TITLE
Send Multi-Part Mime Messages (Plain and HTML)

### ISSUE THREAD

**Issue by goenning** [getfider/fider#486]
**Problem:** Fider currently sends HTML-only messages, which might not work for everyone.

**Solution:** We currently use a custom .tpl file to configure the email templates. Current template should be modified to replace the “body:” parameter with a “html:”. A new parameter “plain:” should also be added to all templates.

Email senders should read both “html:” and “plain:” and set them accordingly during email delivery.

It might also require some changes to current variables sent to templates. We should not create html tags outside templates, all variables should be text only.

**Comment by tomscholz** [comment]
I will look into this, this week. :)

**Comment by FalkW** [comment]
This might also fix my issues I have when reading the mails in Outlook 2007.

![image](https://user-images.githubusercontent.com/12622377/47014054-61e4c300-d149-11e8-9669-4c017ebf4348.png)

**Comment by goenning** [comment]
@FalkW that depends if your email client is configured to use Text message instead of HTML. This issue won't change the HTML version of the email, so you might still see that ugly email if outlook tries to render it.

**Comment by my3** [comment]
@tomscholz are you working on this?
