### ISSUE TITLE
Google OAuth2 isn't working when the users email already exists.

### ISSUE THREAD

**Issue by Sven65** [getfider/fider#503]
**Describe the bug**
On a self-hosted docker instance of Fider, the Google OAuth2 doesn't work.

**To Reproduce**
1. Install Fider through Docker
2. Configure the Google OAuth environment variables to use the ones from google as described [here](https://getfider.com/docs/configuring-oauth/).
3. Try to login with Google.

**Expected behavior**
Expected behaviour is that the user should be shown an OAuth grant screen and then be logged in upon acceptance.

**Actual behaviour**
Actual behaviour is that the user is instead shown an error screen of 
```
Shoot! Well, this is unexpected…
An error has occurred and we're working to fix the problem! 
We’ll be up and running shortly.
```

**Version**
0.15.0

**Additional Details**

Upon doing some testing in an incognito tab of Chrome, it seems to only happen when an account with the email gotten from the Google OAuth exists in the system.

**Comment by goenning** [comment]
Can you run `docker logs <container>` and see if there's anything useful? Because I just tried to Reproduce and I can't. I have even tried the incognito mode. If I login with Google and the email already exists, that provider is attached to the existing user account as expected.

**Comment by Sven65** [comment]
Alright, with the debug option on, it seems like the OAuth2 is unauthorized from fetching a token.

```
app_1  | 2018-08-23T18:26:27.238061934Z ERROR [2018-08-23T18:26:27Z] [WEB] [qpGzNGOjZr9LmF18682mdohRKuvrosbw] Error Trace:
app_1  | 2018-08-23T18:26:27.238114224Z - app/handlers/oauth.go:89
app_1  | 2018-08-23T18:26:27.238155855Z - oauth2: cannot fetch token: 401 Unauthorized
app_1  | 2018-08-23T18:26:27.238164226Z Response: {
app_1  | 2018-08-23T18:26:27.238170627Z   "error" : "invalid_client",
app_1  | 2018-08-23T18:26:27.238177218Z   "error_description" : "Unauthorized"
app_1  | 2018-08-23T18:26:27.238183626Z }
```

**Comment by Sven65** [comment]
It should probably be added that it works for emails that aren't in the system and that I do have 2fa enabled on my google account.

**Comment by goenning** [comment]
That's weird, I see no reason for it to work with one account and not the other. The `oauth2: cannot fetch token: 401 Unauthorized ` happens **before** we fetch the email from Google, so at this stage Fider doesn't even know who you are.

I also have 2FA and it works just fine.

A few searches mention that this could be a misconfiguration (cliend_id & secret), but then it shouldn't work with the other account.

**Comment by Sven65** [comment]
Yeah, it seems like a bit of an edge case, if there's anything I can do to help test the issue and get it fixed just let me know!

If it makes any difference at all, I did create the account with a different email than the one of my google account, which I later changed to.

**Comment by goenning** [comment]
Hi @Sven65, is this still an issue? Have you got any additional information that might help us fix this? Unfortunately there's no way I can reproduce this on my environment.
