### ISSUE TITLE
Missing SMTP settings responds with ERR_EMPTY_RESPONSE and no logs

### ISSUE THREAD

**Issue by iBotPeaches** [getfider/fider#516]
Hi,

I followed the following directions

 * Make `var/fider`.
 * Copy the `docker-compose.yml` file from here - https://getfider.com/docs/hosting-instance/
 * I ran `docker-compose up --build`

I re-ran it a few times, to get a less verbose output

```
db_1   | LOG:  database system was shut down at 2018-09-03 12:35:06 UTC
db_1   | LOG:  MultiXact member wraparound protections are now enabled
db_1   | LOG:  autovacuum launcher started
db_1   | LOG:  database system is ready to accept connections
app_1  | INFO [2018-09-03T12:35:39Z] [MIGRATE] [wNaV68HW8Wr9cmYm0CUEbw8GPgb9aZVq] Running migrations...
app_1  | INFO [2018-09-03T12:35:40Z] [WEB] [TD0LFaS63n2Elb1PPc0GqkISsQfLJTcQ] Application is starting
app_1  | INFO [2018-09-03T12:35:40Z] [WEB] [TD0LFaS63n2Elb1PPc0GqkISsQfLJTcQ] GO_ENV: development
app_1  | INFO [2018-09-03T12:35:40Z] [WEB] [TD0LFaS63n2Elb1PPc0GqkISsQfLJTcQ] http server started on :3000
app_1  | INFO [2018-09-03T12:35:43Z] [WEB] [Zsivq5WgCRNn1SokzU5pQXJ75LG2cs5L] GET http://localhost:9999/ started for 172.18.0.1
```

![76919829-e862-4868-b89e-e28c1af3c846](https://user-images.githubusercontent.com/611784/44989560-412b2a00-af5c-11e8-96ef-3b67f2e8f5fa.jpg)

This is using `fider/master` docker image. The `fider/stable` docker image has same issue.

**Comment by goenning** [comment]
Hi @iBotPeaches 

Did you uncomment `EMAIL_MAILGUN_*` or `EMAIL_SMTP_*` ? If should log an error if you didn't, but it seems like it's not.

**Comment by iBotPeaches** [comment]
Thanks @goenning , that was it. Added my mailgun creds and all is working. Sorry bout that.

**Comment by goenning** [comment]
@iBotPeaches don't worry, you actually found a bug, so thank you! 😁
