### ISSUE TITLE
Store events to allow further protection

### ISSUE THREAD

**Issue by goenning** [getfider/fider#522]
The idea is to create a SQL table to store all sorts of events that happen on Fider. This table would store: Client IP, Event Name and Date. Note that the User would not be stored so that we don't have a link between User and the IP.

Example of events would be: new post, new vote, delete vote, new comment, edit comment, page view, sign in, etc...

We can then mitigate spam / attacks based on Client IP and Event. How that'll be done is yet to be defined. This issue will be used for storing data only.

**Comment by cfilby** [comment]
I'm interested in this one. I'm somewhat new to Go so I want to make sure I understand what I'd need to do to satisfy this PR. From what I've seen in the code, it looks like I'd need to:

* Add a Migration to create the Event Table. This table would contain an id, client_ip, name, created_at (string)
* Create an Event Model.
* Create an EventStorage interface.
* Add EventStorage implementations for in-memory and Postgres.

Is that correct? 

What sort of CRUD methods other than Add would you expect? GetAll? GetByClientIP? Should the event name be free text at the storage level, or would you want named events?

Thanks!

**Comment by goenning** [comment]
@cfilby all your bullet points are correct, although created_at would be a timestamptz and not a string.

I'm thinking that we could use this data for analytics purposes too, like plotting a chart of how many votes/comments/posts have been created per day for the last X days. In that case, we'd need a tenant_id (with its FK), pretty much like all other tables.

This issue is just about collecting the data, so for now the EventStorage could have a Store (or Save) method. We can create the Read operations later on. 

I think that each consumer should be responsible for naming the event. I don't expect that we will have the same event name being generated in multiple places, so that'd not generate any duplicate code.

As for the names, I like what DigitalOcean does, so maybe we could copy it (see picture below)? Our events would be like: `post.create`, `post.update`,`post.respond`, `post.vote`, `post.unvote` (is there such word? 😀), `comment.create` and so on...

<img width="157" alt="screenshot 2018-10-02 at 18 58 48" src="https://user-images.githubusercontent.com/94755/46367368-41ab0380-c675-11e8-800d-f7a24dec3ddb.png">

**Comment by cfilby** [comment]
Whoops! Meant to put that (string) next to the name, not the created_at column. 

I think that resource.action format makes plenty of sense. I'll go ahead and start working on this, thanks!
