### ISSUE TITLE
Generic OAuth `email` missing for Gravatar/E-mail Notifications

### ISSUE THREAD

**Issue by azurewraith** [getfider/fider#526]
I have a working OAuth configuration and successfully tested the `userinfo` endpoint but when users log-in it seems like their E-mail isn't being recorded properly because the Gravatar mapping doesn't show up and E-mail notifications seem to be using part of the name field.

The profile test shows the following: 

Parsed Profile
ID: 3ab<...>25688
Name: Jordan, Robert
Email: Robert.Jordan@domain.com

I attempted to use a name which didn't have a comma inside, but it didn't seem to help the overall behavior.

If it helps, in the profile settings page e-mail seems to be missing on accounts who have OAuth'd.

Thanks,
-Ben

**Comment by goenning** [comment]
Some OAuth providers will prompt user if they want to share their email or not. If they choose not to share, Fider will create an user with a blank email. Or maybe not everyone has an email set on that given OAuth Provider.

Could this be the case?

**Comment by azurewraith** [comment]
I would expect the e-mail to be homogeneous for whoever could access.  This was an intranet endpoint.  On my OAuth login I could see my e-mail in the test profile, but not when I logged in.

I don't recall the OAuth sequence prompting me if I wanted to share my e-mail, but it's possible it could have been early on in the process.  I'll try deleting my cache and trying again.

If a user with a blank e-mail is created via OAuth, I don't seem to be able to add one after the fact (no text field shows up)...

**Comment by goenning** [comment]
I tried to reproduce, but I can't. I have setup a new instance, registered a custom OAuth using Twitch. Logged out and logged in with a completely new email using Twitch. The recently created user had Name and Email set on Fider as expected.

1) If possible, give the following address to one of the users `http://<your-site>/oauth/_xjlkuxxvqe?redirect=http://<your-site>/oauth/_xjlkuxxvqe/echo` (replace _xjlkuxxvqe with your OAuth code), preferable on incognito mode. This will run the same test that you can run on the administration section and will print whatever the user gave access to Fider, so you'll be able to see the payload that is coming back from the OAuth provider.

2) Any user can change/add their e-mail. Go to `Settings` via the menu and click on `change` besides the email field.

**Comment by azurewraith** [comment]
Thanks for checking into it.

1. The test provided parsed ID / Name / E-mail as expected same as the Admin panel test
2. That was actually my bad, I had configured inline CSS to hide the e-mail address form on the sign-in page to force users through OAuth (maybe a decent feature suggestion)... guess the text field has the same ID on the settings page.

I do see my e-mail populated correctly in the profile once I undid my hack, but Gravatar seems like it's not picking it up (another profile with the same e-mail does) and e-mail notifications show an erroneous address:
![image](https://user-images.githubusercontent.com/287646/45173800-33350d80-b1d7-11e8-877c-8ff4bd3f0163.png)

That notification was watched by my other account, so it received the notification.  I'm wondering if multiple recipients are involved the message should be sent BCC instead...

**Comment by goenning** [comment]
Fider **does not** send a single email to two or more recipients. If multiple users have subscribed to a post, Fider will send one email for each.

I believe the problem in this case is that your name contains a comma. The `To` field is `Cochran, Ben <email@company.com` and the server thinks that `Cochran` is recipient 1 and `Ben <email@company.com` is recipient 2. I'll have a look what's the correct fix for this, probably wrap in quotes I'd say.

**Comment by azurewraith** [comment]
Thanks for clearing up the recipient list, it was hard to see because I have two accounts with the same e-mail.

The e-mail notification behavior improved when I manually removed the comma.

I'm guessing the Gravatar issue is because the e-mail address comes back capitalized from the OAuth service where Gravatar does ToLower() on e-mail addresses upon registration.

**Comment by goenning** [comment]
that's a good point, we should definitely do a ToLower() as well if gravatar expects lowercase only
