### ISSUE TITLE
CORS for API endpoints

### ISSUE THREAD

**Issue by nylen** [getfider/fider#531]
I think this is a bug or technical request rather than something for https://feedback.fider.io... let me know if that's not right and I'll move it over.

Here is a simple test page that tries to call out to the Fider API:  https://nylen.io/test-fider.html

If you click the button, this error appears in the console:

>Failed to load https://vote.classicpress.net/api/v1/posts?f=most-wanted: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://nylen.io' is therefore not allowed access.

This could be as simple as just adding `Access-Control-Allow-Origin: *` to all API responses.  Since the token needs to be included in a separate header with each request (?), I don't think this would cause any CSRF issues, and it would definitely be fine for unauthenticated GET requests.

**Comment by goenning** [comment]
I’m not sure if enabling CORS on all API would be a good move. The API endpoints accepts a cookie as well, it’s not mandatory to send the Authentication HTTP Header.

At the moment, the API is intented to be used by Fider itself or a server. 

We can use this issue to discuss about future improvements on this area. What would be the use case for calling the API directly from the browser?

**Comment by nylen** [comment]
We'd like to show feature requests for our product within the product itself. Ref: ClassicPress/ClassicPress#40

Thanks for the additional info - I agree, cookie authentication means that just adding CORS is not a good idea. The standard way to address this is to add a nonce or other CSRF token.

For now, we'll probably build a simple read-only API endpoint to serve as a proxy.

**Comment by goenning** [comment]
@nylen just a heads up, I'm working on the official API documentation (part of #440), until that happens (likely to be mid October/2018), there *will* be some breaking changes. Once published, the API will be frozen and no more breaking changes will be introduced to `/api/v1`. 

Some that *might* affect you:

1) Status are currently returned as numbers, but will be changed to strings. E.g: from 2 to `completed`, 0 to `open` and so on;
2) The querystring filters of `/api/v1/posts` are going to be renamed from `f, q, t` to something like `filter, query, tag`;
