### ISSUE TITLE
SMTP office365 email not sent

### ISSUE THREAD

**Issue by davidbonachera** [getfider/fider#532]
Hi there,

So I tried to use my office365 smtp by setting off my parameter like this :  
```docker
- EMAIL_SMTP_HOST=smtp.office365.com
- EMAIL_SMTP_PORT=587
- EMAIL_SMTP_USERNAME=email@aaa.com
- EMAIL_SMTP_PASSWORD=Ipassword
```

But usually it requires TLS encryption, so I tried to add an encryption method : 
```
- EMAIL_SMTP_ENCRYPTION=tls
```

But still, no e-mail are being sent.

There's no SMTP error in a dev environment inside the docker log, any idea how to debug this situation ? (i'm not an expert in go)

Tks in advance,

**Comment by goenning** [comment]
After some research I found out that Go stdlib `net/smtp`doesn’t support Office365 out of the box. We’ll need use an external package or implement it ourselves. 

For reference: https://gist.github.com/homme/22b457eb054a07e7b2fb

**Comment by chansuke** [comment]
I'd like to pick this up:-)

**Comment by goenning** [comment]
@chansuke you’re more than welcome! 😀

**Comment by goenning** [comment]
I forgot to mention that if you need anything, don't hesitate to ask! I can't promise an answer to all questions, but will do my best!

**Comment by chansuke** [comment]
@goenning thanks!!!

**Comment by goenning** [comment]
This is now possible thanks to @oxynux contribution! 😄

**Comment by davidbonachera** [comment]
Thanks I will wait for the 0.17 release !
