### ISSUE TITLE
Allow for shorter title length 

### ISSUE THREAD

**Issue by tanzaho** [getfider/fider#533]
At the moment, titles needs to have at least 3 words (and 10 char):
https://github.com/getfider/fider/blob/ec4d2794938d5b980bfe65075153be4af4c92918/app/actions/post.go#L36

Often, I'd like to add suggestions such as "Product_name Integration" (which is really clear).

Would anyone see a problem in releasing the constraint here?

**Comment by goenning** [comment]
I might be suspicious to say as I have implemented it, but I prefer larger title.
 
- It might be clear for you, but maybe not for everyone;
- easier to search and thus help avoid duplicates;
- it’s not that restrictive, “add product_name integration” is not that large and is more expressive.

I was actually thinking about adding this to comments also, I’ve been seeing a lot of “I agree”, “me too” and “+1” comments”.

**Comment by tanzaho** [comment]
Ok with the "add product_name integration"
