### ISSUE TITLE
Replace deprecated React lifecycle methods with new approach 

### ISSUE THREAD

**Issue by goenning** [getfider/fider#538]
**Problem:** React is deprecating `componentWillMount`, `componentWillReceiveProps` & `componentWillUpdate` as seen here https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html

**Solution:** We need to remove all occurrences of these method with suitable replacements. We should also try to enable StrictMode https://reactjs.org/docs/strict-mode.html

**Comment by Adlerberg** [comment]
Hello @goenning 
I would like to help with this task, if no one is currently working on it.

**Comment by goenning** [comment]
@Adlerberg it’s open for grabs, so go for it 😀

**Comment by goenning** [comment]
I forgot to mention that if you need anything, don't hesitate to ask! I can't promise an answer to all questions, but will do my best!

**Comment by Adlerberg** [comment]
Hello @goenning. 
I have read your contribution file, but still have some issues with building this app. Can you help me with that?

**Comment by goenning** [comment]
@Adlerberg sure, what's happening? just post the details here.

**Comment by Adlerberg** [comment]
I can not setup the project on my machine to do changes. Maybe, I am missing something.
As it is said [here](https://github.com/getfider/fider/blob/master/CONTRIBUTING.md) I installed Go, node.js and Docker. I also installed Air, Gotoenv and Mage. I executed all comands to sutup development workspace and the status was sucessfull. But, I can not reach to localhost:3000 to see the project.
I tried it both on Windows and Linux Mint Cinnamon and none was successfull. 
Is there any configurations I'm missing?

**Comment by goenning** [comment]
Windows is known to not be compatible yet, we have issue https://github.com/getfider/fider/issues/434 to track that. But it should work on Linux.

Can you run both `mage watch` and `docker ps` and paste here the output?

**Comment by Adlerberg** [comment]
![comm](https://user-images.githubusercontent.com/40995971/46629356-437b3800-cb49-11e8-8dab-b92ec129ef9e.png)

**Comment by goenning** [comment]
Ok, so webpack is working well, but I don't see output from air.

So run `mage watch:server` and paste output

**Comment by Adlerberg** [comment]
Hello @goenning 
Sorry for the delay with the response. I had to re-install my system. Also, every package was re-installed as well. 
This is the output I am receiving  running `mage watch` and `mage watch:server`. 
![server_part_1](https://user-images.githubusercontent.com/40995971/46666038-3e140100-cbce-11e8-8228-b4e3e29455ae.png)
![server_part_2](https://user-images.githubusercontent.com/40995971/46666039-3e140100-cbce-11e8-9681-353721e2e14e.png)
Package godotenv.a is installed on my machine.

**Comment by ganesharulanantham** [comment]
air throws an error /src/github.com/getfider/fider/app/storage: too many open files, error: %!s(MISSING) and nothing could be found in localhost:3000

**Comment by ganesharulanantham** [comment]
> Hello @goenning
> Sorry for the delay with the response. I had to re-install my system. Also, every package was re-installed as well.
> This is the output I am receiving running `mage watch` and `mage watch:server`.
> ![server_part_1](https://user-images.githubusercontent.com/40995971/46666038-3e140100-cbce-11e8-8228-b4e3e29455ae.png)
> ![server_part_2](https://user-images.githubusercontent.com/40995971/46666039-3e140100-cbce-11e8-9681-353721e2e14e.png)
> Package godotenv.a is installed on my machine.
Try installing to execute as cmd

 go get github.com/joho/godotenv/cmd/godotenv

**Comment by Adlerberg** [comment]
Hello @ganesharulanantham 
I executed the code, you sent me, but the output remains the same. 
![cmd1](https://user-images.githubusercontent.com/40995971/46668563-6c490f00-cbd5-11e8-8e4f-0c9e8f98d624.png)

**Comment by goenning** [comment]
As @ ganesharulanantham mentioned, you need to install godotenv as a cmd. Try `which godotenv` to make sure you have that installed.

The issue with `SameSite` is due to Go 1.11. I have recently updated Fider to Go 1.11, so you'll need that to compile current master branch.

**Comment by Adlerberg** [comment]
Hi @goenning 
I keep getting redirected to 404 page. 
Firstly, I was redirected to sign-up page. I entered credentials, at received a modal. After that, I can not reach to any other page. 
What shall I do?

**Comment by goenning** [comment]
Fider has a strong dependency on an email service, be it an SMTP server or a Mailgun account. When you fill in the sign-up page and see the modal, an activation e-mail is sent to the address you've typed in. 

If you didn't setup any email service, have a look on your logs, there'll be a log entry with a message like:

`Sending email to <your-email> ... .... ... http://localhost:3000/signup/verify?k=A_LONG_KEY_GOES_HERE`

Copy this link and paste to your browser. This will activate the tenant and sign you in.

If you don't have the logs anymore, you can purge every row from your database and restart the process.

I guess I need to write a FQA about these issues so that newcomers have a knowledge base to lookup! Thanks for all the comments, they are very helpful!

**Comment by Adlerberg** [comment]
Hello @goenning 
I'm really sorry, but I can not help you with this issue. I tried to resetup the whole project, but still it didn't work for me. I believe, that someone else can do this for you. 
Sorry one more time.

**Comment by goenning** [comment]
Don't need to be sorry, that's actually valuable feedback, I'll see what I can do to make Fider easier to setup. If you have any suggestion, I'm all ears.
