### ISSUE TITLE
List of who voted on the post

### ISSUE THREAD

**Issue by goenning** [getfider/fider#550]
**Source:** https://feedback.fider.io/posts/33/list-who-voted

**Problem:** as an administrator/collaborator, it's not possible to know who voted on each post.

**Solution:** we could add a list of all the users to the right column of the ViewPost page, similar to what GitHub does. This should only be visible to administrators/collaborators and we need to think about how to show a big list of users. We're open to UX suggestions! It should be something nice and clean. Just keep in mind that the list of votes can be anything from 1 to 500, for example.

<img width="1178" alt="screenshot 2018-10-02 at 20 21 41" src="https://user-images.githubusercontent.com/94755/46371774-2d6d0380-c681-11e8-9cc4-2643fe76439e.png">

**Comment by denwwer** [comment]
Hi, I can work on it. I propose to add button under "response" which open modal with list of users?

**Comment by goenning** [comment]
Great! I’m ok with that as a first version! 😀

**Comment by kolten** [comment]
Hello! I started on this yesterday since it seemed up for grabs, came up with this: 
![image](https://user-images.githubusercontent.com/4492824/46827624-b5789a80-cd5e-11e8-97e7-2b2718f8ded2.png)

For the scenario of having more than 5 votes or more (arbitrary), I displayed the first 5 users that voted. You can click the 'Show More', which will open a modal and display this: 
![image](https://user-images.githubusercontent.com/4492824/46827641-c0332f80-cd5e-11e8-8da9-8641ebed2511.png)

Initial thoughts/comments? Thanks!

**Comment by goenning** [comment]
That looks great!, I liked it! My only comments are:

1) Yes, popup should have pictures + scrollable. I'm also wondering if a two columns layout would also look good. You could try it.

2) I'm thinking that'll be really rare when a post has just 5 or less voters, in most cases there are way more voters than that. Showing the only 5 older voters doesn't add much value, but we can't also show everyone. 

So this component initial list is just a "lure" to get people to click on the "Show More" button, because that's where the value is: to see everyone who voted on it. With that in mind, what if we show the avatar of those 4 users, side by side, without the name, and instead of a big "Show More" button, we have a blue link "+ X more", where X is total number of voters - 4.
<img width="1183" alt="screenshot 2018-10-11 at 21 33 06" src="https://user-images.githubusercontent.com/94755/46832188-50906500-cd9d-11e8-9194-06c25c1f36ab.png">

3) On the popup, should we consider an alphabetical order? It the user is searching for someone, that'll make their life easier. In future we might even implement a search box...

What you think?

**Comment by kolten** [comment]
1. Just to clarify with the two columns, you mean one column with the avatar/display photo and the user's name in another column?
2. Agreed, it would also simplify the code I currently have. I also like the + X more! 
3. I like that idea, I can change the current query to send the list of users in alphabetical order.

I just now found how the project is generating avatars, so I'll work on that. 
Do you have any guidelines on testing, by the way?

**Comment by goenning** [comment]
1. No, I mean two columns where each column has both avatar + name. Otherwise there might be a lot of empty space on right side of the popup. Just an idea.

3. I think the list can still be returned by order of vote, but ordered alphabetical on the popup only. Otherwise avatars on the show post page will mostly always be same set of users, those whose name starts with A.

I'm not usually writing much tests for React components, unless they are basic and used very often. You're open to test the way you want, just keep it similar to how we do on other react components. A good example would be a test where we only show the + X more if the list has 4 or more voters.

As for the backend, we need tests for the SQL queries at least.

**Comment by goenning** [comment]
@kolten are you still interested on this issue? It’s ok if you are and need more time! But if you don’t want it anymore, just let me know. I’d like to move this forward and willing to do it myself 😀

Thanks!
