### ISSUE TITLE
Allow users to mention/tag other users

### ISSUE THREAD

**Issue by goenning** [getfider/fider#576]
Source: https://feedback.fider.io/posts/82/allow-users-to-mention-tag-other-users

The goal is to implement exactly what GitHub does when you start typing `@`, where it suggests a list of users to "tag". Whenever tagged, we should send a notification (both e-mail and in-site) about they being mention on that post.

The challenge we have here is that Fider doesn't have username, just Name. More importantly, names can have empty spaces and special character (like @#*!). We could think about a different way of doing so, but using @ is becoming well known pattern, it's something people are getting used to it.

**Comment by ihatetothink** [comment]
I'm thinking about taking this task, would it be for comments or also when creating new suggestions?

I believe we should match "@<not spaces>*<cursor>" does this sound right? 
Also we need a new endpoint that returns all the users right?

**Comment by goenning** [comment]
I'd say just for comments, at least for now. 
I think we can start simple and improve afterwards. What you suggested is good enough. I'd just say that hitting `Enter` should also select the first suggestion.

Yes, we'll need an endpoint where the input is the search term and the result is an array of users with its ID and Name.

**Comment by ihatetothink** [comment]
About the frontend part, can I use some react component library? I'm not that fluent with react

**Comment by goenning** [comment]
I'd rather avoid external libraries. If you have the time, it might be a good moment to level up your react skills with this task. I reckon that is not easy though, but I can help you if you need. 

I'm also not sure how I would implement this, so I'd start with reading other codebases/blogs to see how other people implement such feature.

**Comment by ihatetothink** [comment]
Ok, doing that. 

Also fork is here: https://github.com/ihatetothink/fider for now I have the endpoint

**Comment by goenning** [comment]
You could open a PR, prefix it with [WIP] and ping me everytime you’ve finished part of it.
