### ISSUE TITLE
Burger menu is incorrectly positioned

### ISSUE THREAD

**Issue by goenning** [getfider/fider#580]
As an Admin/Collaborator, go to Site Settings. Resize the browser to the smallest windows size possible. The menu will be collapsed into a burger menu, but it won't be aligned with page title as it should.

<img width="499" alt="screenshot 2018-10-18 at 07 24 36" src="https://user-images.githubusercontent.com/94755/47135190-3a0b7180-d2a7-11e8-813a-e4ffcdf5fbec.png">

**Comment by damcclean** [comment]
I'll see what I can do :)

**Comment by peterver** [comment]
@goenning I'll take a look at this one over the weekend :D
