### ISSUE TITLE
Invalid Posts should return a 404 and not a 500

### ISSUE THREAD

**Issue by goenning** [getfider/fider#581]
**Problem**: at the moment, if we try to navigate to a `View Post` page that doesn't not exist, we'll receive a `500 Shoot! Well, this is unexpected…`, but we should actually receive a `404 Not Found`

**Note:** The same happens to the API, if we try to call `/api/v1/posts/abc`, the response will be 500, but should be 404.

**Comment by peterver** [comment]
I'll take a look at this one over the weekend !
