### ISSUE TITLE
Notify developers when the required CLI tools are missing

### ISSUE THREAD

**Issue by goenning** [getfider/fider#590]
As a Fider Deverloper, there a few external CLI tools required to build and run Fider. They are listed on our Contributing guide: https://github.com/getfider/fider/blob/master/CONTRIBUTING.md

The problem is that if these tools are missing on the developer machine, they won't be able to run it and sometimes the error message is not very helpful. 

We could enhance the `Magefile.go` to verify that the user has the following tools before actually trying to run the actual tools.

- `air` | github.com/cosmtrek/air
- `godotenv` | github.com/joho/godotenv
- `node`
- `npm`

The verification could be a check if that command is available by using `which <cmd>` on macOS/Unix. Windows probably has a similar command. If the CLI tool is not installed, a simple message showing how/where to instal would be great.

**Comment by nclandrei** [comment]
Hi @goenning! Can I take up this issue?

**Comment by goenning** [comment]
@nclandrei yep, go for it :)

**Comment by nclandrei** [comment]
Hey, @goenning! I submitted the pull request and, funnily enough, one of the dependencies (i.e. air) is missing from the CircleCI build environment, so building the PR fails 😁 I propose that air is also installed on CircleCI as this would be the desired environment (i.e. all the required dependencies should be installed on the build env as well). What do you think?
