### ISSUE TITLE
Error during setup for developing on Windows 10

### ISSUE THREAD

**Issue by renatoch** [getfider/fider#603]
> Cannot download "https://github.com/sass/node-sass/releases/download/v4.9.3/win32-x64-67_binding.node":
> HTTP error 404 Not Found

Tried changing to 4.9.4 on package.json, but not sure that's the correct way to fix this.

**Comment by goenning** [comment]
Hey, are you using Node.js 11? If so, then that’s the issue. Because node-saas does not yet provide binding for node 11 (it’s a very recent release).

That’s why you beed Python to compile it yourself.
