### ISSUE TITLE
Questions to make the Dockerfile better

### ISSUE THREAD

**Issue by qdm12** [getfider/fider#651]
Hi there,

First, sorry for the multiple issues all in one. I am working on making your Dockerfile build everything with a multi stage build amongst other improvements. One little thing that would help me, although I could do it, would be to switch to go modules using `golang.org/x/vgo`. This way the multi stage build would be much more developer friendly with fast build cycles.

A few improvements I'm trying to add:
- Dockerfile builds everything from source (Node and Go)
- Multi stage build for fast development and testing
- Runs without root
- Runs Go unit tests
- Final image based on Scratch

I will make a PR as soon as you switch to go modules, or I'll stick to dep.

**Comment by goenning** [comment]
How would vgo help on this regard? 

I’d like to switch to modules, I haven’t done that yet as I was waiting for go 1.12 to come out, as with 1.11 it’s still an experimental feature.

I’m also concerned that go modules could slow down the CI builds. I’m not sure, that’s just a guess.

I’m looking forward to see how would the multi stage build look like, those improvements got my attention ! 😀

**Comment by qdm12** [comment]
Hi there !

Actually you are right, I just could not figure out some Dockerfile/Dep quirks but it works now, so no need to move to modules. I'm still working on the Dockerfile and it would be great if you could confirm the following:

1. To compile the frontend you need:
    - NPM
    - Directories: `etc`, `public` and `tests`
    - Files: package-lock.json package.json tsconfig.json webpack.config.js
1. To compile the backend you need:
    - Go, Dep
    - Directories: `app` (maybe `vendor`?)
    - Files: Gopkg.toml Gopkg.lock main.go
1. How do you run frontend tests? With `npm install`?
1. Can you run backend tests with only `go test` or do you really need Mage?

Thanks a lot! I will continue working on it tomorrow and it should be finished tomorrow.

**Comment by goenning** [comment]
1. Yes, I guess that’d be all.
2. I use mage test:ui, but is it common to run testing when building the docker image? I’d say that the CI is responsible for making sure that the tests are passing before any merge to master. I think Docker should just build the app and ignore the tests.
3. See the mage build file. It uses npm behind the scenes
4. You don’t actually need Dep or the Gopkg files. The main.go and the whole vendor folder should be enough.
5. Same as point 2, do we to run it?

Also, have a look at getfider/circleci Docker image. That image contains Go, NPM, Mage and everything you need to build all Fider assets. The Dockerfile for this image is also open source (on this GH Organization) and it’s used by our CI process, so that’s guaranteed to always be up to date. We could probably use that image on the builder step.

**Comment by qdm12** [comment]
Thanks! I'll have a look at Mage and that CI Dockerfile. Usually tests are quick to run. If it's the case as well, it's good to run them at Docker build. It also makes sure tests don't fail because of a host issue.

Do you manage both vendor and dep or do you prefer one?

The Dockerfile should look [similarly to that](https://github.com/qdm12/fider/blob/master/Dockerfile) sorry if it's scary at first! It's not finished yet.

**Comment by qdm12** [comment]
Hi there,

I have (I hope) a working Dockerfile. You can check latest commits [here](https://github.com/qdm12/fider/commits/master). I however can't test after the sign up page because my mail server is not configured yet. Would you mind having a quick look to see if it works?

```bash
git clone https://github.com/qdm12/fider.git fider_fork
cd fider_fork
docker-compose -f docker-compose-prod.yml build
# Change email env variables in docker-compose-prod.yml or use .env file
docker-compose -f docker-compose-prod.yml up
```

And try accessing it at [localhost:9999](localhost:9999), depending on your env variables. 

I will test it once I finish my mail server, probably in a week or so.

Added features are:
- Quick re-build time
- **13.6MB** resulting docker image based on Scratch
- Runs frontend tests at build
- Runs without root at all at runtime

Todos:
- Backend tests (need to a postgre server and client to the builder container, or do without db)
- Add Docker labels

Undecided yet...
- Use Mage eventually or stick to what Mage does under the hood?
- Compress the Go binary with UPX (depending on RAM usage)

Thanks!

**Comment by goenning** [comment]
Thanks for the working on it. Allow me some time to review and understand it. The only thing I noticed is that our current docker image is 9MB, I was expecting that this image would be smaller than that.

**Comment by qdm12** [comment]
The `getfider/fider:stable` is *19.7MB* (id `042bbd5e0c63`). The 9MB is probably the download size which is compressed. The difference in size is just Alpine (5MB=19.7-13.6) really though.

**Comment by goenning** [comment]
Alright, that makes sense.

As for the undecided topics:

- I really would like to keep Mage within docker. That's where we put all instructions to build/test/run/whatever, I don't want to maintain two sets of instructions. We used to use Make, but that's awkward to use on Windows, so we switched to Mage.
- I'd not mix UPX on this PR. Let's make it a separate discussion on that after this one is complete. 

Questions:

- do we need all those ENV variables inside docker-compose-prod? or is it just for testing purpose? Will we be able to remove later on?
- any benefits on having so many builders? I'd rather concentrate on having a single docker builder (https://github.com/getfider/circleci) which is used by both this Repo and our CI, that's easier to maintain IMO. That builder contains everything that we need, including Mage, godotenv and a postgres client.

As for your changes, I tried building it with `docker-compose -f docker-compose-prod.yml build` and I got this error (I'm on a mac): 

```
ERROR: Service 'app' failed to build: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/bin/sh\": stat /bin/sh: no such file or directory": unknown
```

**Comment by qdm12** [comment]
> I really would like to keep Mage within docker. That's where we put all instructions to build/test/run/whatever, I don't want to maintain two sets of instructions. We used to use Make, but that's awkward to use on Windows, so we switched to Mage.

Ok I'll work on using Mage

> I'd not mix UPX on this PR. Let's make it a separate discussion on that after this one is complete.

Agreed

> do we need all those ENV variables inside docker-compose-prod? or is it just for testing purpose? Will we be able to remove later on?

These are environment variables your application supports from reading your documentation. I could set them to nothing but it's generally good to have them in the Dockerfile for self-documentation purposes. 

> any benefits on having so many builders? I'd rather concentrate on having a single docker builder (https://github.com/getfider/circleci) which is used by both this Repo and our CI, that's easier to maintain IMO. That builder contains everything that we need, including Mage, godotenv and a postgres client.

I will check your CI Dockerfile again. The point is to build the Docker image directly from github, without any third party like CircleCI. For development as well, it's much faster to build the image locally first before using CI tools.

For the many builders, there are only two really, one for Go, one for react. It's just that the stages are split to save time by caching layers. For example if you build the image once, building it again with changed go files will be much faster. For example the entrypoint is not at the end of the Dockerfile because it rarely changes usually, whereas instructions dependent on go code for example are the top layers. 

Finally, in my case for production purposes, I always enjoy to have a Dockerfile I can build directly with ` docker build -t name https://github.com/getfider/fider` as I don't trust Docker Hub with non-automated builds.

**Comment by qdm12** [comment]
> We build Fider without Docker during the development process, so that's very important. There are also companies using Fider outside Docker, where they build it from source. Mage is an additional dependency, but it makes the build process much simpler for whoever wants to build it from source.

Agreed, that's why I don't want to change Mage to fit Docker. I could however add some functions in the magefile, and it could play out nicely. I will look into that.

> One image is the CircleCI builder, and the one in this repo is our App image.

We could thus replace the App Dockerfile with this one, and leave CircleCI alone for now?

> But if we do combine them and do everything in a single Image like you're mentioning, we'll probably lose the parallelism we have today.

I just searched online, thanks for mentioning about parallelism, I never thought about it! And there is apparently an experimental `--parallel` flag for multi stage builds, see [this](https://github.com/moby/moby/pull/32402). I will try soon ! Thanks for your response.
