### ISSUE TITLE
Migration errors when Installing Fider without Docker

### ISSUE THREAD

**Issue by digitalore** [getfider/fider#653]
I'm receiving migration errors when installing Fider without Docker. 
I used the contribute file as a guide for installing fider without docker.  I removed the docker references, installed the necessary/remaining dependences (golang, node, etc) and for the most part it was all pretty painless. Docker isn't needed because our postgres database is always running in a separate instance. 

I'm able to connect to the postgres database via the .env file without error and I am even able to run "mage build" successfully. However, when attempting to run "mage watch" or "mage run" I receive the migration "exit status 1" error. 

(Running Migrations... exit status 1)
- failed to insert log (app/pkg/log/database/logger.go:139)
- failed to execute trx.Execute (app/pkg/dbx/dbx.go:126)
- pq: relation "logs" does not exist

It seems that a few tables are created and the migration doesn't complete. When I check the postgres database only the following tables were created/are available:

- comments
- email_verifications
- idea_subscribers
- idea_supporters
- idea_tags
- ideas
- migrations_history
- tags
- tenants
- user_providers
- user_settings
- users

Any feedback or assistance on this would be greatly appreciated. I simply would like to successfully install fider without Docker. Also, Is there any special requirements or modules that are needed for the database?

![image](https://user-images.githubusercontent.com/2564667/48990483-a7a78a80-f0fc-11e8-9614-8625f1c44505.png)

**Comment by goenning** [comment]
That reminds me that we need `pg_trgm` extension on Postgres. Fider tries to create this extension if not already created, but that requires special permission. Can you check if your Postgres instance has this extension? If not, create it with:

```
CREATE EXTENSION pg_trgm;
```

**Comment by digitalore** [comment]
Tried this, it's installed... same errors.

**Comment by goenning** [comment]
This is likely to be a bug, but I’m not sure the log you posted here is the root cause. The migration process tries to log the progress on the database, even if the table doesn’t exist yet. But this is a silent error, it shouldn’t halt the process, hence why some tables have been created.

Can you lower the log level to DEBUG, purge the database and run it again? Please post be full log here.

Thank you!

**Comment by goenning** [comment]
I found the issue that was not logging all the details during the migration. That's merged to master, so you'll need to pull again and recompile it. I don't expect it to fix the problem, but it should help troubleshooting it.

**Comment by digitalore** [comment]
This the error that I am receiving now that I have the latest build/recompiled. 

> INFO [2018-12-03T01:41:40Z] [MIGRATE] [gmA55PFx0dvp4UIbT8ICPo6UbtzFKi9e] Running                Version: 201802071816 (201802071816_seed_subscribers_table.up.sql)
> **ERROR** [2018-12-03T01:41:40Z] [MIGRATE] [gmA55PFx0dvp4UIbT8ICPo6UbtzFKi9e] Error                Trace:
>-  failed to run migration '201802071816_seed_subscribers_table.up.sql' (app/pkg/               dbx/migrate.go:69)
> -  pq: syntax error at or near "ON"
> 2018/12/03 01:41:40 exit status 1
> Error: running "godotenv -f .env ./fider" failed with exit code 1
>

**Comment by digitalore** [comment]
I was able to get it to work, finally. Unfortunately, my host was blocking a migration process because of memory and a login distinction. I was able to update the user but afterward, I received a 502 error because of port 3000 which is declared in the \cmd\server.go - I am using a custom port.

All in all, thanks. The logging update helped tremendously.

**Comment by digitalore** [comment]
Yes, this is resolved.

**Comment by yachal-upson** [comment]
@goenning I seem to have run into this behaviour while trying to raise a docker Fider instance. 
#1095 

DB logs are full of the following:

> 2022-10-10 05:56:39.415 UTC [33] STATEMENT:  INSERT INTO logs (tag, level, text, created_at, properties) VALUES ($1, $2, $3, $4, $5)

2022-10-10 05:56:39.453 UTC [37] ERROR:  relation "logs" does not exist at character 13
2022-10-10 05:56:39.453 UTC [37] STATEMENT:  INSERT INTO logs (tag, level, text, created_at, properties) VALUES ($1, $2, $3, $4, $5)
2022-10-10 05:56:39.479 UTC [33] ERROR:  column "created_at" of relation "logs" does not exist at character 37
