### ISSUE TITLE
Asset URLs not loading properly

### ISSUE THREAD

**Issue by jamesecwalker** [getfider/fider#692]
We've had Fider running fine on an Azure App Service Docker Container for about 5 or 6 months now, but suddenly it's stopped loading all the assets such as scripts and stylesheets so we just get a blank screen.
Looking at the loaded page, it seems that the asset URLs aren't getting generated correctly and are referencing localhost instead of the 'host' http header e.g. http://127.0.0.1:44856/assets/css/common.618ee9e044fadc620b1d.css
Is there something that's changed in the latest release?

**Comment by goenning** [comment]
Are you on version 0.17.0? I suspect this is the same issue: https://github.com/getfider/fider/issues/666

This is fixed on master, but has not been backported to 0.17.0. You can either update to master or wait for 0.17.1. I’ll try to do it this weekend.

**Comment by goenning** [comment]
Another update, version 0.17.1 (also tagged as stable) is now on available. Give it a try please.

**Comment by jamesecwalker** [comment]
Hiya
Yes that seems to have fixed the issue!
Many thanks
James
