### ISSUE TITLE
Docker container randomly crashes

### ISSUE THREAD

**Issue by Sven65** [getfider/fider#721]
On version `Fider v0.18.0-6334`, when clicking around in the admin panel the container seems to crash randomly after a few requests.

@GottZ was with me at time of testing since he handles the server stuff for our project.

**Comment by Sven65** [comment]
Might be related to #720

**Comment by GottZ** [comment]
crashes stopped after upgrading psql from `9.6` to `11.1-alpine` but it's still kinda slow in terms of responsivenes in comparison to before. we upgraded to `v0.18.0-6334`. we were on `v0.17.04618` before.

**Comment by GottZ** [comment]
no it just turns into a zombie

**Comment by goenning** [comment]
The only thing I noticed is that during development, where I use LOG_LEVEL=DEBUG, it would freeze when there was many concurrent requests. Raising to INFO would reduce that, while WARN completely  solved the problem. That was very rare though, but I guess there's an issue with logging, hence why I was the LOG_LEVEL.

**Comment by Sven65** [comment]
From what I can see, the issue occurs when you click around too much too fast, especially in the admin panel.

**Comment by Sven65** [comment]
closing this in favor of #720
