### ISSUE TITLE
How to build docker image from source

### ISSUE THREAD

**Issue by franz-see** [getfider/fider#731]
I tried following CONTRIBUTING.md

| Software  | How to install | What is it used for |
|---|---|---|
| Go 1.11+ | https://golang.org/ | To compile server side code |
| Node.js 10+ | https://nodejs.org/ or run `nvm use` if you have nvm installed | To bundle client side code |
| Docker | https://www.docker.com/ | To start local PostgreSQL instances |
| cosmtrek/air | `go get github.com/cosmtrek/air/` | Live reload for Go apps |
| joho/godotenv | `go get github.com/joho/godotenv/cmd/godotenv/` | A `.env` file loader |
| magefile/mage | `go get github.com/magefile/mage/` | A cross-platform Make alternative |

I installed Go, Node, and Docker

I did `go get` on `cosmtrek/air`, `joho/godotenv`, and `magefile/mage`, but that doesnt seem to be enough. 

The first error was missing air dependencies. So I went to `$GOPATH/src/github.com/cosmtrek/air/` and `make install` and that installed it. And I installed mage via https://magefile.org/#installation . 

Then I tried running `mage build:docker`, and now I am getting 

```
exec: go build -ldflags -s -w -X main.buildtime=2019.03.08.000535 -X main.buildnumber= -o fider .
main.go:7:2: cannot find package "github.com/getfider/fider/app/cmd" in any of:
	/usr/local/go/src/github.com/getfider/fider/app/cmd (from $GOROOT)
	/Users/franzsee/go/src/github.com/getfider/fider/app/cmd (from $GOPATH)
main.go:8:2: cannot find package "github.com/getfider/fider/app/models" in any of:
	/usr/local/go/src/github.com/getfider/fider/app/models (from $GOROOT)
	/Users/franzsee/go/src/github.com/getfider/fider/app/models (from $GOPATH)
main.go:9:2: cannot find package "github.com/getfider/fider/app/pkg/env" in any of:
	/usr/local/go/src/github.com/getfider/fider/app/pkg/env (from $GOROOT)
	/Users/franzsee/go/src/github.com/getfider/fider/app/pkg/env (from $GOPATH)
main.go:10:2: cannot find package "github.com/lib/pq" in any of:
	/usr/local/go/src/github.com/lib/pq (from $GOROOT)
	/Users/franzsee/go/src/github.com/lib/pq (from $GOPATH)
Error: running "go build -ldflags -s -w -X main.buildtime=2019.03.08.000535 -X main.buildnumber= -o fider ." failed with exit code 1
```

Here's my environment

```
OSX 10.14.3
Node v10.15.1
Go version go1.12 darwin/amd64
Docker version 18.09.3, build 774a1f4
```

**Comment by goenning** [comment]
Thank you for this very detailed report!

Because this project is not yet using Go Modules, Go expected the source code to be on `$GOPATH/src/github.com/getfider/fider`. It looks like your GOPATH is `/Users/franzsee/go/ `, can you confirm if this folder contains the source code?

Try this: 

```
ls $GOPATH/src/github.com/getfider/fider
```

It should list all folders from this repository.

**Comment by franz-see** [comment]
Thanks @goenning You're right. I was able to build it when I did a symlink (`ln -s /Users/franzsee/path/to/my/cloned/fider $GOPATH/src/github.com/getfider/fider`)

Then from `$GOPATH/src/github.com/getfider/fider`, I executed `mage build:docker` and that worked.

Honestly though, Im not sure if I did anything else aside from that. I tried a bunch of things and right now I cant remember anything else I did to get it building :)

**Comment by goenning** [comment]
Good to know! I’m closing this now. Feel free to re-open if you hit another wall 🙂
