### ISSUE TITLE
Mailgun has 2 base URLs (US and EU)

### ISSUE THREAD

**Issue by Khazuyo** [getfider/fider#744]
Hey there!

I've - so far - successfully set up a local Fider installation and hooked it up to Mailgun. Within the sandbox everything's okay but as soon as I went into productive mode and tried sending via a real domain, this happened:

`app_1  | DEBUG [2019-03-21T14:54:00Z] [WEB] [Hrtp1bfMHsjwMJZAXwEf3owvoRsrmHfd] Email sent with response code 404.`

It turns out that Mailgun as 2 base URLs now
- https://api.eu.mailgun.net/v3/ for "EU domains"
- https://api.mailgun.net/v3/ for "US domains"
and sadly they aren't exchangable.

Using the "correct" API via curl on the command line works fine.
My Fider installation, however, can't send mails because the URL seems to be hardcoded (app/pkg/email/mailgun/mailgun.go) and the US API doesn't know about my EU domain.

I assume that I will have to recompile Fider myself if I want to fix this?

**Comment by goenning** [comment]
Good point. We have hardcoded the US endpoint. Multi-region was not supported when we did the integration.

And you're also correct, you'll need to change the source and recompile if you want to use the EU domain.

If you want to contribute, I would happy to accept a PR with that option being configurable :)

I can see a new configuration `EMAIL_MAILGUN_REGION` with valid options as blank, EU or US. Then mailgun.go would use the correct domain based on configuration. A blank setting would default to US.

**Comment by Khazuyo** [comment]
Well, I am already setting up a development VM on my Windows PC because I kind of want to do more than just compiling Fider on my server just to hot-swap the binary.
I'll try coming up with something and will start a PR when I think that the patch is mature enough.
Not sure how fast I'll progress though, I've never worked with Go before.

**Comment by Khazuyo** [comment]
Quick heads up: I already have the code running on a server I am using for a game dev project I'm leading. If you are curious, you can look at it in a separate branch, "mailgun-region-env" which is in my fork of the project's repo.

I haven't created a PR yet because some things are missing, namely the tests, but I'll catch up with that as soon as I am able to. (:

**Comment by goenning** [comment]
@Khazuyo that's an amazing work, thanks very much! Looking forward to the PR 😀

by the way, did you manage to get Fider running on Windows? Because I though that was not possible yet (ref: https://github.com/getfider/fider/issues/434).

**Comment by Khazuyo** [comment]
Not directly - whenever I can I use VMs and/or Docker to isolate build processes. It also has the advantage that I can just tear down and set up containers again if I need to, like after tinkering with some settings.
