### ISSUE TITLE
Triple dot button on members list not opening menu for users create with API

### ISSUE THREAD

**Issue by peku33** [getfider/fider#748]
We are in process of integrating fider in our business. Using api ( https://getfider.com/docs/api/#create-user ) we synced all users from our directory to fider.

However when I click on members list trying to promote any user to administrator no dropdown is shown. No errors are logged to console.

![image](https://user-images.githubusercontent.com/8615581/55718718-ad8f6f80-59fc-11e9-853b-10a55d8873d4.png)

Users may normally log into fider.

I reversed api call to "promote" button on current user and successfully managed to mimic this action by replacing user id. For "manually" edited users dropdown works.

**Comment by goenning** [comment]
Thanks for reporting this bug. I have just fixed it so please give it another go 😀

**Comment by peku33** [comment]
Can confirm it's fixed now, thank you!
