### ISSUE TITLE
SSL certificate path problems

### ISSUE THREAD

**Issue by bblaha** [getfider/fider#752]
I'm trying to set up an SSL certificate for fider, but the mounting does not work according to the documentation (or I'm doing something wrong).
I am using let's encrypt, so the certs have to be mounted from the host system.
The certs are at /etc/letsencrypt/live/*DOMAIN*, I have a cert.pem and a privkey.pem there.
In the docker-compose.yml I added
- /etc/letsencrypt/live/*DOMAIN*:/app/etc according to the documentation
Checking the container after startup I can see the files at /app/etc.

When I add the environment variables
SSL_CERT: cert.pem
SSL_CERT_KEY: privkey.pem

I get the following error at startup: 
```
app_1  | panic: Error Trace:
app_1  | - failed to start server (app/pkg/web/engine.go:148)
app_1  | - open etc/cert.pem: no such file or directory
app_1  |
app_1  | goroutine 29 [running]:
app_1  | github.com/getfider/fider/app/pkg/web.(*Engine).Start(0xc000259dc0, 0xc00013dd74, 0x5)
app_1  |        /go/src/github.com/getfider/fider/app/pkg/web/engine.go:148 +0xbb3
app_1  | created by github.com/getfider/fider/app/cmd.RunServer
app_1  |        /go/src/github.com/getfider/fider/app/cmd/server.go:24 +0xd4
```

I am out of options on what else to try, I have tried using different mounting points, different environment variable paths and so on.

**Comment by goenning** [comment]
I **believe** those files under /etc/letsencrypt/live are just symlinks. If that's the case, can you try using the actual files and not symlinks? Another option is to check how is the read permission. Maybe the process is unable to read those files.

**Comment by bblaha** [comment]
Yes, you are right. The actual files are in archive, not live. I thought of that as well and tried the ones in archive before, but got the same result.

**Comment by goenning** [comment]
What docker image are you using? getfider/fider:stable? 

If you connected to the container and you can `cat /app/etc/cert.pem`, then I don't know what it could be. I have a similar setup here, the only difference is that I'm using docker directly instead of docker-compose, but that shouldn't make any difference.

**Comment by bblaha** [comment]
Yes, I'm using the stable image you mentioned.
And I can connect to the container and do whatever I like with the cert in that location, so it definitely is there.
As soon as I add the environment variables to the docker compose file (may that be the problem?) it does not even boot, so I can't check if the file is there after adding the environment variables.

**Comment by goenning** [comment]
That image should already have `/app` as the working dir, but just to be sure, you can try adding `working_dir: /app` to your compose file. 

Also, can you share your complete compose file?

**Comment by bblaha** [comment]
Sure, attached it to this post. I did remove the mail and facebook section as I think those would not cause the problem.
I have tried adding the working_dir, same result.
[docker-compose.txt](https://github.com/getfider/fider/files/3088349/docker-compose.txt)

**Comment by bblaha** [comment]
Reading over it again I am wondering if this might still be a path problem, since the error message relates to etc/cert.pem. Is it supposed to just show the partial path? Should I maybe try another (non-stable) build?

Also I'm wondering if maybe the volume does not get mounted in time for whatever reason... But then again: The error repeats over and over again, so at some point it should be mounted.

**Comment by goenning** [comment]
All the file reads happens from the working dir, which why is important for it to be /app

Another image should not make any difference.

Which files do you have under `/etc/letsencrypt/archive/*domain*`? At least on my system, those files are named cert1.pem and privkey1.pem.

Just to rule out the possibility of having something wrong with the `/etc/letsencrypt/archive` directory, try to create an empty cert.pem and privkey.pem under any other folder and mount that as a volume. Fider should complain that the content is not well formatted, but at least it should find those files.

**Comment by bblaha** [comment]
Oh wow, that was really it. I'm terribly sorry!
It appears the symlinks would not work and I just forgot to add the 1 add the end of the filename for the real path. Done that, now it works.
Thanks for your help and sorry for putting you through that trouble for an error on my side.
