### ISSUE TITLE
MacOS build process not working?

### ISSUE THREAD

**Issue by takuy** [getfider/fider#754]
I get this when trying to run launch Fider in a browser. I've built Fider while following the directions in the Contributors doc. Browser just reports: "Shoot! Well, this is unexpected…"

```
INFO [2019-04-23T12:31:12-04:00] [WEB] [1rrBJtQp6vs3G905NuVJtwcRipUmxPRK] GET http://localhost:3000/ started for ::1
DEBUG [2019-04-23T12:31:12-04:00] [WEB] [1rrBJtQp6vs3G905NuVJtwcRipUmxPRK]  SELECT t.id, t.name, t.subdomain, t.cname, t.invitation, t.welcome_message, t.status, t.is_private, t.logo_bkey, t.custom_css,  tb.trial_ends_at AS billing_trial_ends_at,  tb.subscription_ends_at AS billing_subscription_ends_at,  tb.stripe_customer_id AS billing_stripe_customer_id,  tb.stripe_plan_id AS billing_stripe_plan_id,  tb.stripe_subscription_id AS billing_stripe_subscription_id FROM tenants t LEFT JOIN tenants_billing tb ON tb.tenant_id = t.id ORDER BY t.id LIMIT 1  [] executed in 4ms
ERROR [2019-04-23T12:31:12-04:00] [WEB] [1rrBJtQp6vs3G905NuVJtwcRipUmxPRK] Error Trace: 
- app/middlewares/tenant.go:31
- failed to get first tenant (app/services/sqlstore/postgres/tenant.go:300)
- failed to execute trx.Get (app/pkg/dbx/dbx.go:277)
- pq: relation "tenants" does not exist
INFO [2019-04-23T12:31:12-04:00] [WEB] [1rrBJtQp6vs3G905NuVJtwcRipUmxPRK] GET http://localhost:3000/ finished in 14ms (rolled back)
```

**Comment by goenning** [comment]
There was an issue where `mage watch` was not running database migrations, it's now fixed on master. Please pull latest changes and try again.

**Comment by takuy** [comment]
Thanks, @goenning. I still ran into an issue - while `mage watch` did the database migrations, I still had to do a `mage run`.

`mage watch` reported: `/bin/sh: /users/me/go/src/github.com/getfider/fider/godotenv: no such file or directory` despite godotenv being properly installed. 

So, `mage watch` -> `mage run` solved my problem after your fix on master.

**Comment by goenning** [comment]
Weird, because mage run uses godotenv too. But good to know it's solved.

**Comment by takuy** [comment]
Yeah, I'm not entirely sure what's going on, but it seems like at some point, with watch, it just ends up trying to execute godotenv from the wrong directly.
