### ISSUE TITLE
fider.io self hosted on Server 2019

### ISSUE THREAD

**Issue by zamarax** [getfider/fider#759]
Hi everyone, I see that in the docker-compose.yml that the DB it's requesting is postgres:9.6 which isn't supported on Server 2019 as there is no manifests file for it, it is possible for fider to be updated to use v11.

Or is it at all possible to get this working on Server 2019? Currently I get the following error when attempting to pull for it.

`PS C:\ProgramData\docker\volumes\fider> docker-compose pull
Pulling db  ... pulling from library/postgres
Pulling app ... pulling from getfider/fider

ERROR: for db  no matching manifest for windows/amd64 in the manifest list entries

ERROR: for app  image operating system "linux" cannot be used on this platform
ERROR: image operating system "linux" cannot be used on this platform`

**Comment by goenning** [comment]
Postgres 11 should be fine, I have used before and haven't seen any issue. As for the Fider itself, as of now, it'll only run on Linux. Can't Docker for Windows run Linux containers too? At least on Windows 10 that is possible through Hyper-V

**Comment by zamarax** [comment]
Linux containers on Windows is hit and miss, requires a certain kernel level...etc...etc... I tried it with fider and it kept throwing an error.
