### ISSUE TITLE
Cannot enable Facebook, Google, and GitHub on Heroku

### ISSUE THREAD

**Issue by mtpiercey** [getfider/fider#761]
On the OAuth 2.0 configuration page on the docs website, [https://getfider.com/docs/configuring-oauth/](https://getfider.com/docs/configuring-oauth/), there isn't any advice on how to actually enable Facebook, Google, and GitHub OAuth integration on an instance hosted on Heroku. 

I tried changing the environment variables, then I tried deleting the database and starting over, but they're still disabled.

Any help would be appreciated. Thanks!

**Comment by goenning** [comment]
Adding those environment variables to your Heroku instance and restarting the app should do it. There’s no need to delete the database.

**Comment by mtpiercey** [comment]
OK. I figured that I wouldn't need to delete the database. I tried adding the variables (for Google and GitHub), then restarted the app, but those specific providers still seem to be disabled.

**Comment by goenning** [comment]
We recently noticed that the documentation had the wrong environment variable names. It was fixed on this PR https://github.com/getfider/getfider.com/pull/9 

That might help you.

**Comment by mtpiercey** [comment]
Excellent work. That did it.

(I figured it was something small like that but I never would have found that). Thanks!
![image](https://user-images.githubusercontent.com/22581026/66778418-99d83080-ee99-11e9-9f08-bb2a0b21ebf2.png)
