### ISSUE TITLE
Disable Post Creation Based on User Role

### ISSUE THREAD

**Issue by asommer70** [getfider/fider#762]
I was wondering if this feature request is being worked on [disable-suggestions-for-non-admins](https://feedback.fider.io/posts/79/disable-suggestions-for-non-admins)?

If not I would like to work on it and if anyone has any pointers, suggestions, etc I'd love to hear them.  Here are the things I think need to be adjusted to implement this feature:

* Adjust the Go code for adding a post to check user role.
* Adjust the API Go code to check user role.
* Adjust the React code to not display the suggestion form if user has a role that isn't permitted.
* Add a form to the Settings for choosing a role to allow which roles, and above, can create posts (will default to 1/visitor).
* Create a migration for adjusting the tenants table adding a create_posts field.
* Update the Tenant model for the create_posts field.
* Create documentation for the changes.
* Add tests for the changes.

So that's the plan, if anyone has any feedback I'd love to hear it.

Thanks all!

---
Updated to include adding a migration and changed from disallowing to configuring which roles will be allowed.

**Comment by goenning** [comment]
It seems like you covered everything 👍

Ideally the roles should be a separate table and permissions would be attached to it, but we are not there yet, so this is the best we can do right now.

**Comment by SamTheGeek** [comment]
A suggestion for the UI: Leave the suggestion form enabled but suppress the description, attachments, and submit button. This allows the submission box to offer (admittedly duplicative) functionality like the search box, especially since it is a clearer CTA.

**Comment by asommer70** [comment]
@SamTheGeek that's a good idea.  I'll look into doing that.

I've changed the IsAuthenticated method (or whatever the correct name is in Go) to check the Tenant in the context:

```
// IsAuthorized returns true if current user is authorized to perform this action
func (input *CreateNewPost) IsAuthorized(ctx context.Context, user *models.User) bool {
	// Disallow for unauthenticated users
	if user == nil {
		return false
	}

	// Get the tenant from the context
	tenant, ok := ctx.Value(app.TenantCtxKey).(*models.Tenant)
	if !ok {
		return false
	}

	// Check user.Role is greater than Tenant.CreatePosts
	if int(user.Role) < tenant.CreatePosts {
		return false
	}

	return true
}
```

What I'm not sure of is how to write a test for that?  It's probably due to my fledgling Go skills, but any pointers would be greatly appreciated.
