### ISSUE TITLE
No correct way to use a reverse proxy server with SSL enabled?

### ISSUE THREAD

**Issue by deseven** [getfider/fider#764]
I'm not sure about this, but there is no info about it in docs and it looks very much broken.

If i use nginx as a reverse proxy server with SSL enabled (`proxy_pass http://localhost:9999`, etc), all urls generated in Fider become broken, for example:
`http://https://mydomain.com/assets/js/main.c486a2a654473fa3a9f6.js`

**Comment by lisek84** [comment]
Got the same problem, but In my case, I can see proper url but always with http instead of https.
Tried redirecting this on nginx site, but it didn't work.

**Comment by goenning** [comment]
Is nginx sending the X-Forwarded-* to Fider?

These headers are expected for Fider to know how to build the assets URL

**Comment by deseven** [comment]
Yes, i use a pretty typical config:
```
proxy_set_header X-Forwarded-Host $host;
proxy_set_header X-Forwarded-Server $host;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Real-IP $remote_addr;
```

**Comment by deseven** [comment]
Wait, looks like adding  
`proxy_set_header X-Forwarded-Proto https;`
fixed it.

I'm gonna test everything again and update this issue later.

**Comment by lisek84** [comment]
This helped me too. Works like charm. Thank You.
