### ISSUE TITLE
Building Fider Docker Image from Source

### ISSUE THREAD

**Issue by asommer70** [getfider/fider#767]
I'm trying to create a Docker image from source, but I'm running into the following error:

```
app_1  | /bin/sh: ./fider: not found
fider_app_1 exited with code {u'StatusCode': 127, u'Error': None}
```

The Fider code works perfect when running ```mage run``` (and ```mage watch```), but when I execute ```sudo docker build -t getfider/fider .``` I get the error above.

Am I missing something in the .env file or the Dockerfile?

Thanks, I appreciate your help.

**Comment by asommer70** [comment]
I think I figured it out.  I added **libc-compat** to the alpine image:

```
 RUN apk update && apk add ca-certificates libc6-compat
```

Simply edited line 2 of the Dockerfile.  I came up with the fix from this thread: https://stackoverflow.com/questions/36279253/go-compiled-binary-wont-run-in-an-alpine-docker-container-on-ubuntu-host/36308464

The other options didn't seem to work for me, but adding *libc6-compat* did.

**Comment by goenning** [comment]
There’s a mage build:docker that creates an image from source, but I might actually change the Dockerfile to have a build step and then remove this mage task, that would be easier for people to understand as that’s the way it’s done on most projects
