### ISSUE TITLE
Migrate from tslint to eslint

### ISSUE THREAD

**Issue by goenning** [getfider/fider#775]
might be a good first issue for people doing the Hacktoberfest 🙂

**Comment by dvfleet413** [comment]
@goenning I'd be willing to work on this if it's still open

**Comment by goenning** [comment]
Yes, it’s still open. By the way, we want to continue using prettier as well, so the plan is to migrate from tslint+prettier to eslint+prettier

**Comment by dvfleet413** [comment]
Great, thanks for clarifying. I’ll work on it tonight, should have a PR in the next few days.
