### ISSUE TITLE
Unable to run fider locally

### ISSUE THREAD

**Issue by chagriali** [getfider/fider#793]
Hello,

I'm getting an exception related to the database I think when I run the project locally. It's a fresh repo with no changes.
![Screenshot from 2019-10-26 23-43-22](https://user-images.githubusercontent.com/22005100/67626969-7c1cab00-f84b-11e9-80c4-45a0f6b1562d.png)
Can you please help me on this ?

**Comment by goenning** [comment]
How did you start Fider? Did you use `mage watch`?

It’s missing the database migrations, which should be executed before the app starts

**Comment by goenning** [comment]
I think it's a bug and fixed on #799. The app was starting before the migration was complete. Can you pull the latest from master and try again? Thanks 👍

**Comment by chagriali** [comment]
Yes, it's working now thanks :)
