### ISSUE TITLE
Multiple tenants in the same database

### ISSUE THREAD

**Issue by ArtemAnchugov** [getfider/fider#822]
I've noticed that code and database structure allow to have multiple tenants in the same database. 
I configured 2 fider instances pointing to same Postgres database, but both websites show same data and database have only 1 tenant.

How can we add second tenant to existing database or/and configure fider instance tenentId?

**Comment by buremba** [comment]
What prevents you from creating another database for the other app?

**Comment by ArtemAnchugov** [comment]
@buremba Nothing prevents from creating another database but having one database makes some sense for me. Here is some background:
- At this point we want to gather feedback in 2 languages, so we set-up 2 instances.
- Both sites are to gather feedback for same product.
- We will add more languages soon.

Having one database for all feedback for the product is more convenient than having multiple databases for these reasons: 
1. Querying aggregated data, searching for data, reporting, etc is easier with one DB
2. When we add more languages => more databases, making things more difficult
3. We hope that at some point, when multi-language support is implemented, won't need multiple instances of fider. It would be nice to have data in one place at that point.

**Comment by goenning** [comment]
Multi tenant doesn't work with two applications, you need to have a single app and turn on multi tenancy. As far as I can remember, the only change is to add this env vars:

```
HOST_MODE=multi
HOST_DOMAIN=yoursite.com
```

That'll turn your app into multi-tenant. Each tenant will have its url as `<tenant subdomain>.yoursite.com` . You can then later add a custom CNAME if you wish.
