### ISSUE TITLE
Fider stops responding occasionally

### ISSUE THREAD

**Issue by GoldRenard** [getfider/fider#823]
Sometimes Fider stops responding and client browsers are getting connection timeout error.
I have to restart it to get it working back but this happens again and again.

I'm using current stable version (0.18.0).
Searching through the other issues, I tried to set the `LOG_LEVEL` to `WARN`, didn't helped tho.

**Comment by jessepelley** [comment]
This describes the problem I'm having as well. 

It seems to only happen when someone connects, though it's random. They can be loading the main page or editing a post. 

Nothing shows up in logs.
