### ISSUE TITLE
Fail to query post/user and so on by API. 

### ISSUE THREAD

**Issue by lijun1234** [getfider/fider#827]
Issue: Fail to query post/user and so on by API. 
Fider version:  V 0.18
Setting: Privacy is enabled.

```
Authentication
curl -H "Authorization: Bearer {api key generated under admin user account}" https://<fqdn of fider site>:9999
response
app_1  | INFO [2019-11-05T23:41:29Z] [WEB] [A0HIU5tmW6BQyF2B40E8j6EPOPpew7eC] GET https://<fqdn of fider site>:9999/ started for <ip>
app_1  | INFO [2019-11-05T23:41:29Z] [WEB] [A0HIU5tmW6BQyF2B40E8j6EPOPpew7eC] GET https://<fqdn of fider site>:9999/ finished in 3ms (committed)

query post
curl -X GET https:// <fqdn of fider site>:9999/api/v1/posts
response
 app_1  | INFO [2019-11-05T23:43:43Z] [WEB] [BJqiC5QPd5aTya3hdTnxEoO8kMcOVyDD] GET https://<fqdn of fider site>:9999/api/v1/posts started for <ip>
app_1  | INFO [2019-11-05T23:43:43Z] [WEB] [BJqiC5QPd5aTya3hdTnxEoO8kMcOVyDD] GET https://<fqdn of fider site>:9999/api/v1/posts finished in 3ms (committed)
```

Could someone point where is the problem.

Thank you.

**Comment by goenning** [comment]
I don't get what's the problem here. What is the response and what did you expect?

**Comment by lijun1234** [comment]
Hi Goenning,

Sorry I didn't explained well. I try to use api to query fider users accounts and posts. The fider site is on premise with private enabled.  I type the command like below to auth https connection and query the post. I expect to see the posts but I actually get API Key is invalid error
![fider](https://user-images.githubusercontent.com/6380633/69252586-2bc70d80-0bab-11ea-9e00-2ac47894c4f5.png)

The API key is fresh generated from an account with administrator role. Confirmed this administrator account can login and manage the site. 

Thank you

Jun

**Comment by goenning** [comment]
Lower log levels to DEBUG and do it again. You’ll see the SQL command that was executed. Try that same command directly in your database, it’s very likely that Fider cannot find a user with that key.

**Comment by lijun1234** [comment]
The fider is setup according to [Hosting your own instance](https://getfider.com/docs/hosting-instance/). Neither steps over there nor [api document](https://getfider.com/docs/api/) explain how to lower log levels to Debug level.
However I do see in docker compose file there is option  GO_ENV. 
1. Does debug level mean setting this key to development value? 
2. Since compose up the containers in background, where can I find fider log running in container? Of course I can compose down containers and compose up container and see the log from console but it's good to know the log file on the file system instead of on the screen. 

Thank you for your time and effort. 

Jun

**Comment by goenning** [comment]
You can do that by setting the LOG_LEVEL env variable to `debug`. I don't know where docker store the logs, I usually check the console or the postgres database on the logs table.

**Comment by lijun1234** [comment]
I stop the containers and start the new containers. This time curl query works. Not sure what happen to the previous containers. Mark this issue resolved
