### ISSUE TITLE
Issue with CSP

### ISSUE THREAD

**Issue by mantoshelis** [getfider/fider#831]
I'm this issue here because there is no other chat where we can discuss about this issue.
I do get error while trying to open Fider website. It is hosted on Docker Swarm and HTTPS. Seems like CSP is not configured for Ajax scripts.

`Content Security Policy: The page’s settings blocked the loading of a resource at https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js (“script-src”).`

**Comment by shakeelosmani** [comment]
I have the same issue above. What was your work around?

![image](https://user-images.githubusercontent.com/9120484/182430154-b50d4424-2189-4803-afca-4f1f109418d7.png)
