### ISSUE TITLE
Redirect HTTP requests to HTTPS

### ISSUE THREAD

**Issue by ArtemAnchugov** [getfider/fider#832]
An option to redirect all HTTP traffic to HTTPS. (via env var setting?)

It would be nice to have an option to force Fider to redirect all HTTP requests to HTTPS equivalents.

If SSL is configured for an app, we might want to forbid HTTP traffic altogether. (Allowing HTTP when HTTPS is enabled has some security implications).
When Fider is hosted in Heroku, it seems there is [no way to control redirects via Heroku](https://help.heroku.com/J2R1S4T8/can-heroku-force-an-application-to-use-ssl-tls). Quote:

> Issue
You have configured an SSL endpoint and now you want your application to use https for all requests.

> Resolution
Redirects need to be performed at the application level as the Heroku router does not provide this functionality. You should code the redirect logic into your application.

When behind SSL-terminating reverse-proxy (like Heroku router) Fider can determine protocol used by http client via **X-Forwarded-Proto**  and **X-Forwarded-Port** headers.

> Under the hood, Heroku router (over)writes the X-Forwarded-Proto and the X-Forwarded-Port request headers. The app must check X-Forwarded-Proto and respond with a redirect response when it is not https but http.

**Comment by kabouzeid** [comment]
Any news on this?

**Comment by justinesgar** [comment]
I also would like to know how to do this. Heroku keeps you from accessing .htaccess or any other code to do the redirect. For now, we have the link in our system pointing to https:// - but we don't want anyone to accidentally fall on the http:// version

**Comment by pedr0-fr** [comment]
I solved this by having cloudflare redirecting all HTTP traffic to HTTPS:


![image](https://user-images.githubusercontent.com/16596928/91636097-e6672480-e9f5-11ea-9a17-50f60eb9b78c.png)

**Comment by ktaragorn** [comment]
This is getting critical.. it appears chrome atleast is blocking login attempts via http.

**Comment by ktaragorn** [comment]
I was able to get it working in a way by redirecting from javascript as in this patch file, Ideally should be done by the backend, but I felt the go code was a lot harder for me to parse. (had to rename to .txt to let github upload it)


[0001-Force-HTTPS.patch.txt](https://github.com/getfider/fider/files/5287715/0001-Force-HTTPS.patch.txt)

**Comment by goenning** [comment]
@ktaragorn @justinesgar @ArtemAnchugov I'm not using Heroku, so can someone pull the code from https://github.com/getfider/fider/pull/934 and give it a go please? Thanks
