### ISSUE TITLE
Triple Dot Button on Members List Not Opening Menu for Users Created with API (Round 2)

### ISSUE THREAD

**Issue by jimmybrancaccio** [getfider/fider#836]
It seems like #748 may have resurfaced again. I imported about 50,000 users to my Fider instance last night and I can't seem to click on the triple dot icon for any of those imported. Here's an example of one of those imported users from PostgreSQL:

```
-[ RECORD 2 ]+----------------------------------------------------------------------------------------
id           | 62
name         | keukmooeer
email        | b********@j*********.org
created_at   | 2020-01-03 21:29:55.349966+00
tenant_id    | 1
role         | 0
status       | 1
api_key      |
api_key_date |
avatar_type  | 2
avatar_bkey  |
```

I did adjust the email field (obviously 😝 ). Is the role value correct for an imported user?

 If there's any other information I can provide to help, don't hesitate to ask!

**Comment by jimmybrancaccio** [comment]
No, bad stale bot, this needs to be fixed!

**Comment by goenning** [comment]
@jimmybrancaccio No, role should be 1. Are you running the latest version? And did you import using the API or direct SQL insert?

**Comment by jimmybrancaccio** [comment]
Hey @goenning I've got another issue with `201904022134_lowercase_emails.sql which I've opened an issue for in #935. I noticed there's an SQL migration which updates all the roles which are 0 to 1, which I assume would fix this issue.

**Comment by jimmybrancaccio** [comment]
Ok, I think we're all set now being on the latest version, having figured out #935 and all. For what it's worth users are created via the API, so hopefully now that's working properly. I'll re-open if there's further issues (I'm in the process of rebuilding my site so it'll be some time before I can re-test).
