### ISSUE TITLE
Name tooltip on avatar image (via title)

### ISSUE THREAD

**Issue by esgn** [getfider/fider#837]
Think there's something missing in https://github.com/getfider/fider/blob/master/public/components/common/Avatar.tsx 

I  added "name: string;" in AvatarProps>user and set title to {props.user.name} in the img tag. Seems to work ok in order to get the username via simple tooltip on mouse over.

`interface AvatarProps {
  user: {
    role?: UserRole;
    avatarURL: string;
    name: string;
  };
  size?: "small" | "normal" | "large";
}`

`return <img className={className} title={props.user.name} src=.../>;`

**Comment by goenning** [comment]
hey @esgn, yep, apparently we missed that property. Want to send a PR?

**Comment by esgn** [comment]
Ok. I will very soon. Thx
