### ISSUE TITLE
Automatic registration for trusted openid providers

### ISSUE THREAD

**Issue by chrnin** [getfider/fider#838]
Hi,

I'm deploying fider in my organization with my own instance and I'd like to set my instance in private mode to prevent unwanted users to connect and read contents.
I set up a self hosted openid provider (keycloak) where I manage all users and I can trust every sign-in coming from it.
My issue is that if I activate private mode, I have to invite all users on fider in addition of creating them in keycloak, given that this creation would be a sufficient way to trust connections.

My wish would be to let administrators enable a kind of « public mode » (in the way it creates profiles automagically) for chosen openid providers.

Is that in your plans ? Would you like some help to achieve it ? By the way, if there's a better idea, I'll love it for sure ;)

Regards,

Christophe

**Comment by TimNilimaa** [comment]
This would be very handy. Currently we are working with IP whitelist in the host, but it is very limiting as not all our browser traffic goes through a corporate wide VPN (none actually...).

**Comment by TimNilimaa** [comment]
Also, this "JIT" (Just In Time) creation of accounts from trusted IDPs are quite normal scenario I'd say...

**Comment by chrnin** [comment]
For the moment, I commented these 3 lines in app/handlers/oauth.go (lines 104,105,106) and deployed a custom binary…
```
if c.Tenant().IsPrivate {
   return c.Redirect("/not-invited")
}
```

This enables the automatic creation for all oauth providers, btw it's not suitable if there are big providers like google or facebook and privacy concerns, but it perfectly fits my own needs for the moment.

**Comment by chrnin** [comment]
I tried something more elaborated than the 3 lines obfuscation with PR #839… I'll wait a bit to push this one in production ;)

**Comment by sebastiansirch** [comment]
+1 for this issue / PR. I want to deploy a fider instance in our company using OAuth (Azure AD) as authentication. The instance has to be private, but I don't want to invite all users manually since the group of users is already defined (and managed) by Azure AD.

**Comment by delewis13** [comment]
+1 same use case!

**Comment by Aikatsui** [comment]
Additionally request to add following documentation but need to be supported in web-app
https://docs.weblate.org/en/latest/admin/auth.html#openid-authentication
(opensuse, ubuntu, fedora....)

**Comment by carlreid** [comment]
@goenning Any thoughts on how this could be solved? I need the same thing, where the instance is private by I trust the oauth provider, so would like users to be created automatically.

Can https://github.com/getfider/fider/pull/839 be worked on/merged to solve this?

**Comment by jens-hoeppner** [comment]
+1 from my end as well!

**Comment by carlreid** [comment]
We use Traefik as a load balancer, so as as a work around we ended up using [ForwardAuth](https://doc.traefik.io/traefik/middlewares/http/forwardauth/) and [traefik-forward-auth](https://github.com/thomseddon/traefik-forward-auth) to authenticate the user before it hit the Fider service.

That way, we can keep Fider as "public" so accounts are created by default when logging in 🎊

**Comment by goenning** [comment]
This is now a feature! Thanks @chrnin for the PR 🎉

![image](https://user-images.githubusercontent.com/94755/168412798-2d389fb5-6401-4179-9c69-05ed0f1ff885.png)
