### ISSUE TITLE
Ability to remove test ideas

### ISSUE THREAD

**Issue by pavel-odintsov** [getfider/fider#84]
Hello!

Thank you for an awesome project! I just deployed your SaaS version for my OSS project: https://fastnetmon.fider.io/ 

It works really cool!

But I want to remove my test idea to publish it for our customers. And I could not find button to do it :(

**Comment by goenning** [comment]
Hi @pavel-odintsov, I'm happy to support your OSS project! :)

It's not possible to remove an idea. However, what you can do is Decline it by using the Respond button. 

Not having a delete button is intencional, it's a mechanism to protect customers from having their ideas thrown into a trash bin. The url is permanent, once created it will never be undone. Pretty much like a GitHub issue.

Does it make sense?

**Comment by pavel-odintsov** [comment]
Hello!

Thank you! It makes sense. I just moved this Fider instance to production! :)
