### ISSUE TITLE
Email encoding issue

### ISSUE THREAD

**Issue by kfuglsang** [getfider/fider#844]
The email notifications sent out have incorrect encoding in all dynamic content fields.
Danish letters are formatted as question marks "?".

**Comment by goenning** [comment]
Hey @kfuglsang could it be something on the SMTP?

I tried with mailgun and it worked ok.
<img width="731" alt="Screenshot 2021-08-17 at 20 44 27" src="https://user-images.githubusercontent.com/94755/129790341-73e75c7b-fce8-461b-89d2-bfd59c4b2ec8.png">

**Comment by Chocobozzz** [comment]
Hello,

We also have an issue with email subjects that contain quotes. They are replaced with HTML code.

![screen_2022-07-21-11:06:08](https://user-images.githubusercontent.com/5180488/180176162-03970c9e-b6e6-462e-be74-f3c5acbad142.png)

Email header:

```
...
Subject: [Letâ€™s improve PeerTube!] it&#39;s the network that matters.
MIME-version: 1.0
Content-Type: text/html; charset="UTF-8"
...
```

Maybe related to https://github.com/getfider/fider/blob/c9c55b2f5b33a76015241b97e03cfac1254b42a7/app/services/email/message.go#L38?
