### ISSUE TITLE
Email addresses unwittingly published openly

### ISSUE THREAD

**Issue by almereyda** [getfider/fider#850]
When creating an account, logging in and reacting to a post by upvoting it, it is nowhere said that the email address of a user will be published openly. In Europe, this can cause problems due to the General Data Protection Regulation (GDPR), since an email address is a personal datum. Using and processing it needs explicit and individual consent. This already might be a seperate issue in itself. This one is yet closely related.

After clicking to **see details** of the list of voters, there will be email addresses publicly visible without explicit consent given before.

The expected display only shows the user names, and does not reveal the identity with which they registered at the platform.

Ultimately, if one gets the consent beforehand, and wishes to republish these personal facts of the users, there could be a small Site Setting that allows to switch display modes.

**Comment by s3cur3** [comment]
This is a blocker for any business trying to use Fider... it probably _should_ be a blocker for anyone _in general_ using it. 😕

My team's going to take a look at fixing this, and a handful of other GDPR compliance issues, because we'd really like to use Fider rather than the commercial alternatives.

**Comment by almereyda** [comment]
Thanks in advance for the efforts. I'd volunteer to review and test a PR,
if that aids the process of merging it.

Tyler A. Young <notifications@github.com> schrieb am Mi., 22. Juli 2020,
16:03:

**Comment by goenning** [comment]
As @s3cur3 , this is only for admins/collaborators
