### ISSUE TITLE
Serve Fider from folder

### ISSUE THREAD

**Issue by rhuanbarreto** [getfider/fider#851]
Hi! Thanks for this great piece of software!

I'm trying to run Fider on a proxied subfolder in NginX like

```
server {
  server_name maindomain.com;
  listen 80;
  location /feedback/ {
    proxy_pass http://proxiedaddress:9999/
  }
}
```

But all assets still get pointed to the root address like `http://maindomain.com/assets/Home.Page.ddvwjwdnvjkee.css` instead of `http://maindomain.com/feedback/assets/Home.Page.ddvwjwdnvjkee.css`

Is that something that I could do to have it working?

**Comment by rhuanbarreto** [comment]
Is it something to do with using relative paths on the templates instead of absolute?

**Comment by blastah-code** [comment]
Bump. I'm having the same problem as well. Any idea of how to resolve this?

**Comment by rhuanbarreto** [comment]
No way for now. I had to use a subdomain to serve.

**Comment by rohanraarora** [comment]
Hi I am facing the same issue. Is there a way to host fider on subdirectory?

**Comment by rhuanbarreto** [comment]
Today there's no option. Go is not my main language so I can't help much.

**Comment by RappyTV** [comment]
why's this closed? i also need this
