### ISSUE TITLE
First Look + MultiTenant

### ISSUE THREAD

**Issue by rossbuggins** [getfider/fider#852]
Hi - just having a look, and seems like could solve a problem pretty well. One quick question, I see from the [feature request](https://feedback.fider.io/posts/127/allow-grouping-feedback-by-application-category) that category / boards / apps are being discussed which is great.
In the mean time, I was looking at the multi tenant as an option, which i have working - however, is there an admin page that i havn't found for deleting / editing this globally and also a way of disabling the http://localhost:9999/signup page? Thanks

**Comment by goenning** [comment]
No, there is no admin, but there’s an env variable to disable signup (which may be removed in near future).

multi tenant is not a replacement for categories and currently not documented, so expect unannounced breaking changes there, avoid if you can
