### ISSUE TITLE
Update setup docs

### ISSUE THREAD

**Issue by rossbuggins** [getfider/fider#853]
It probably makes sense to update the [setup docs](https://getfider.com/docs/hosting-instance/) to use the version of [docker-compose.yml ](https://github.com/getfider/fider/blob/master/docker-compose.yml) that includes the mailhog smtp server

**Comment by mipapo** [comment]
Why?  
For testing: yes
But most people will just use the docker compose for production

**Comment by goenning** [comment]
That Docker compose is meant to be used for development as @mipapo mentioned
