### ISSUE TITLE
Roles / Tags

### ISSUE THREAD

**Issue by svperfecta** [getfider/fider#858]
We're looking to use OAUTH scope to unlock access to various tags.  For instance, doing so might allow a user who owns a specific product to access the tag for that product.  This will help ensure feedback comes from users who actually have experience with it.  To do that, we'd like to expand the roles feature, and then potentially assign roles based on OAUTH scopes.  When the role is assigned, tags would be associated with the role.

I wonder if there's any interest in this feature in core, or should we develop this in a fork.  If there's interest, and pointer / suggestions about how you'd like the work done?

**Comment by goenning** [comment]
For feature suggestions, please use https://feedback.fider.io
