### ISSUE TITLE
Translation - Google Translate

### ISSUE THREAD

**Issue by svperfecta** [getfider/fider#859]
Hey Team - We'd like to add support for an optional Google Translate dropdown, embedded in the HTML of the page and enabled through the settings feature.  Is there any interest in having this feature in the core of the product?

**Comment by uNitrous** [comment]
+1

**Comment by mipapo** [comment]
Maybe better use deepl.com? 
But yes - sounds like an good idea

**Comment by Aikatsui** [comment]
https://github.com/getfider/fider/issues/575

**Comment by goenning** [comment]
We now have built-in translations provided by the community. 

https://crowdin.com/project/fider
