### ISSUE TITLE
panic: Path 'dist' not found

### ISSUE THREAD

**Issue by mehmetkose** [getfider/fider#860]
Hi, I followed these heroku instructions; https://getfider.com/docs/hosting-on-heroku/

And I ended up here;

![Screen Shot 2020-05-04 at 00 20 25](https://user-images.githubusercontent.com/706678/80926031-29ddb900-8d9d-11ea-8218-2395bcaa113d.png)

what you suggests?

**Comment by akrantz01** [comment]
I'm running into the same issue. Are there any updates?

**Comment by mehmetkose** [comment]
hey @akrantz01 Just add node.js build pack and go pack both. "Repeat the operation with the nodejs buildpack. You should now have two buildpacks listed in this section."
