### ISSUE TITLE
Cannot get SMTP SSL working

### ISSUE THREAD

**Issue by MarekSuchanek** [getfider/fider#865]
I tried to set up Fider but could not get SMTP SSL working (standard port 465) - only allowed by our main mail server. Then I tried Gmail again with SMTP SSL, still the same. But with TLS/STARTTLS 587 it is working.

Please can you give me some hints what am I doing wrong? I really doubt that only TLS/STARTTLS is supported 😃 

Also related issues (which are not "solved" in my opinion): #849, #772

**Comment by goenning** [comment]
@MarekSuchanek can you check if the new environment variable introduced on this PR ( https://github.com/getfider/fider/pull/926 ) fixes the problem? You can now disable STARTLS.

Please reopen if the problem persists.
