### ISSUE TITLE
Help with custom OAuth

### ISSUE THREAD

**Issue by delewis13** [getfider/fider#870]
Hello,

I have no Go experience, so it is likely a very silly question, but I cannot seem to get display_name or email to resolve correctly for a custom OAuth provider [patreon].

My OAuth settings:
![settings](https://user-images.githubusercontent.com/20104413/88479265-2c614080-cf91-11ea-931e-6607a89fd4c6.png)

My test result:
![test result](https://user-images.githubusercontent.com/20104413/88479268-2ff4c780-cf91-11ea-9ab6-014045fa0964.png)

I did some inept debugging. Traced error to line 45 of jsonq.go:
`json: invalid number literal, trying to unmarshal "\"daniel.elliott.lewis@gmail.com\"" into Number`

Any help would be greatly appreciated!

**Comment by goenning** [comment]
@delewis13 can you pull the latest version see if it’s resolved? Reopen if not please. Thanks.
