### ISSUE TITLE
How to prevent writing to the logs table?

### ISSUE THREAD

**Issue by rampatra** [getfider/fider#872]
I am using Heroku free version to host fider and it's only a month now and I'm getting emails regarding too many rows in my postgres table. They have a limit of 10000 rows in the free version and I am very close.

Can I prevent writing to this table? If yes, I would like to know where to disable it?

Thanks for making this software free. It is wonderful :)

**Comment by hriziya** [comment]
Yes, there is a way.  You have to specify this settings.

go to "app/pkg/env/env.go"

```
Log struct {
	Level string `env:"LOG_LEVEL,default=NONE"`
}
```

**Comment by ktaragorn** [comment]
Just to clarify @hriziya's point. The current setup is set to log at level INFO, which is a lot of logging. You can set `LOG_LEVEL` in heroku to be ERROR or as @hriziya  suggested, NONE to disable (or mostly disable in the case of ERROR). The code already exists and changing the env var is all that is needed.

**Comment by rampatra** [comment]
From what I understand, you have to change the log level in code as mentioned by @hriziya. I do not think you can change this on Heroku.

**Comment by ktaragorn** [comment]
I was able to test and verify that you can change the LOG_LEVEL in heroku config vars to get the desired effect, before posting here.

**Comment by rampatra** [comment]
@ktaragorn ah, I see. This is even better then. Thanks for the insight. 👍

**Comment by rampatra** [comment]
I have tried both the solutions and none of them worked for me. Any ideas?

**Comment by goenning** [comment]
@rampatra still need help? We seem to have a bug whereby "NONE" is not actually valid. 

Try "ERROR" to log only errors (which should be rare), or send us a PR, should be something on app/pkg/log/level.go

**Comment by ktaragorn** [comment]
Yup, to clarify my point, I changed `LOG_LEVEL` in heroko vars to `ERROR`
