### ISSUE TITLE
Serverless hosting

### ISSUE THREAD

**Issue by abeMedia** [getfider/fider#873]
Hey guys.

Love Fider! It's a great piece of kit! I just have a question regarding hosting it.

Right now I'm using Docker but I was wondering if it works on Serverless architecture e.g. AWS Lambda or Google Cloud Functions?

For this to work there is obviously some work involved in wrapping the API into serverless endpoints and then pushing the frontend onto a CDN like CloudFront but before I get to work on this I just wanted to verify that the app is actually stateless and therefore suitable for Serverless architecture.

By the way I'm happy to contribute this back to the project as I believe it can benefit a bunch of people (cost savings, scalability etc.).

**Comment by cad** [comment]
I believe you can try running it on CloudRun as a serverless container w/ an external PostgreSQL database.

**Comment by zaptrem** [comment]
@cad @abeMedia Could this also be done by putting the whole app in a Google Cloud Function with their Go runtime?

**Comment by abeMedia** [comment]
@zaptrem most likely. You could transform events from lambda or gcf to `http.Request` instances and pass them straight to the handler.

I was asking here if the app is stateless to see if that would work and I although I assume it would be fine I can't say for sure without an answer to my question.

**Comment by goenning** [comment]
Fider is stateless and although this might be possible with extra code/mapping, it’s not something I’m looking to support at the moment. One of the reasons we only support Docker is to have a an agnostic hosting platform.

Google Cloud Run is serverless and supports Fider, but I don’t know if AWS/Azure have something similar.
