### ISSUE TITLE
URLs of custom OAuth providers transformed to lowercase automatically

### ISSUE THREAD

**Issue by tobiashinz** [getfider/fider#880]
I tried to connect my Fider instance to Keycloak.

My Keycloak realm has a capital letter in its name. Fider transforms the Authorize URL, Token URL and Profile API URL to all lowercase automatically. 

This way it is a realm-name mismatch with Keycloak and the authentication fails.

I was able to work around it by changing the mentioned URLs in the database.

**Comment by spadge4711** [comment]
Same for me... Unable to use it with oauth2 though

**Comment by goenning** [comment]
Should be an easy fix, I didn’t know URLs are case sensitive. Anyone interested in submitting a PR?

**Comment by indyteo** [comment]
I can do it, it doesn't seem to be much complicated: #973

**Comment by goenning** [comment]
Thanks for the contribution @indyteo 👍
