### ISSUE TITLE
Is fider still maintained?

### ISSUE THREAD

**Issue by tobiasschuerg** [getfider/fider#883]
There wasn't a new release since more than a year and there are many open PRs. 
Is this project still maintained or is it dead?
Any alternative which you would recommend instead?

**Comment by thepill** [comment]
Would also love to know about the status of this project 👍

**Comment by goenning** [comment]
I'm haven't had time to work on Fider and I'll sunset the hosted fider.io this year, so yeah, we can consider it dead.

As for alternatives, this project was inspired on https://github.com/ivandiazwm/phpback (although it seems to be unmaintained right now). There is also https://github.com/riggraz/astuto, but I don't know much about it.

**Comment by temporallyaccount** [comment]
This's a nice and very useful project for everyone with good features. 
@goenning i doubt, this might be only the opensource project you have that people get benefit widely? 
Can't you really spare some hours for a month to fix some bugs or work in new features even not regularly to keep that project active? i dont think that's difficult for a developer like you. Any thought?

**Comment by gistsy** [comment]
+1 from me @goenning to keep maintain this project.

**Comment by RolphH** [comment]
Maybe others would like to maintain the project (bug fixing at least, PR reviewing/merging)?

**Comment by daniel-sc** [comment]
Maybe adding a (paid/freemium) hosted service might make development more sustainable?

This could be done either by the initial maintainer @goenning or some third party. 

Maybe a license change might facilitate this. Either AGPL (for original maintainer) or MIT should be fine.

**Comment by applewiskey** [comment]
Is sponsorship will help you continue to maintain product or maybe there are some other options as license changes / project transfer ?

**Comment by m3nu** [comment]
The content from the `backup.zip` wasn't straight-forward to import into a new database (Heroku for me). So made this Python import script. Sharing it here for the benefit of other users who are forced to migrate.

https://gist.github.com/m3nu/1228a25b883ae8c49de471d0c8d37b90

This imports all data and files (attachments, logos, user avatars).

**Comment by matusfaro** [comment]
I'm looking for early adopters on my [product](https://clearflask..com) which I will give this community **free** for lifetime in exchange for your feedback. If you're interested, send me a message to setup your account and to migrate your data.

There are a lot of other commercial alternatives on the market (50+). These alternatives typically include a powerful search and analytics engine that becomes useful in managing a LOT of feedback. Below are alternatives that I believe are worth checking out starting from the most affordable:

- [Upvoty](https://upvoty.com)
- [Nolt](https://nolt.io)
- [ClearFlask](https://clearflask.com) (Shameless plug)
- [Canny](canny.io)
- [Aha](https://aha.io)
- [Pendo](https://pendo.io)
- [UserVoice](https://uservoice.com)

@goenning Let me know if you want me to remove this post

**Comment by RolphH** [comment]
@matusfaro this looks interesting. Is there a self-hosted version too? I'm definitely interested.

**Comment by matusfaro** [comment]
> @matusfaro this looks interesting. Is there a self-hosted version too? I'm definitely interested.

There is not, something that will be available down the road if there is enough demand. It would be quite heavy though as it has dependencies on ElasticSearch, CloudFront, DynamoDB, RDS, S3, Zookeeper, etc...

**Comment by uNitrous** [comment]
It's about :/
> @goenning  I'm haven't had time to work on Fider so yeah, we can consider it dead.

Don't take away this project from him and maybe some volunteer developers can join to contribute and maintain this project, eventually @goenning may find enough time to work. Hey! FOSS lovers ʕ•́ᴥ•̀ʔ

**Comment by Glennrs** [comment]
I'm the founder of Noora (https://noorahq.com) - anyone using the hosted version of Fider is welcome to give us a try. We're also able to offer bootstrapped discounts where applicable, as well as help get your data from Fider into our platform. Bonus: we have a light & dark theme 👍

**Comment by emilbryggare** [comment]
If anyone is looking for a hosted alternative, Convas (https://convas.io/) is free to get started and always free for open-source projects (non-commercial).

I'm the founder of Convas - if you have questions or want help with migration just reach out to me at emil@convas.io. 🙂

**Comment by goenning** [comment]
If you're using Fider, can you please help me over here https://github.com/getfider/fider/issues/899 ? Thanks

**Comment by asaqib27** [comment]
> Don't take away this project from him and maybe some volunteer developers can join to contribute and maintain this project, eventually @goenning may find enough time to work. Hey! FOSS lovers ʕ•́ᴥ•̀ʔ

I would like to maintain this project..
what's say @goenning ??

**Comment by goenning** [comment]
hey all, it’s been more than a year since I became inactive on this project. A lot has happened since and I feel like I’m in a better place now to resume working on Fider again. The difference this time is that I won’t be making a monthly commitment on deliveries like I did before, or live and breathe this project. Ultimately it all led me to a burn out and impacted everyone, not just me.

Going forward I’ll keep the project alive, review issues and PRs and implement new features at a slower pace to avoid going stale again. My priority for the immediate term is to get the project up to date with packages/security updates, clean up old/stale issues, review all PRs, improve the docs and streamline the setup process as a lot of people seem to struggle with it currently.

Based on some feedback in #899, simplicity and OSS have been reason a lot of people chose Fider, so those will remain at the core of what we do going forward.

**Comment by pYFZOS5** [comment]
Hooray! 🥳🤪
Kindly don't forget to review there're some [closed issues](https://github.com/getfider/fider/issues?q=is%3Aissue+is%3Aclosed)

**Comment by chrisonline** [comment]
Great news!!
