### ISSUE TITLE
Has anyone deployed using Kubernetes?

### ISSUE THREAD

**Issue by javierguzman** [getfider/fider#902]
Hello all,

I am making a web app and I would like to use Fider for customer feedback. I am trying to deploy Fider using Kubernetes but I keep getting  the following error:
```
ERROR [2021-01-27T08:31:28Z] [MIGRATE] [srOcJxwc2jvHI0Zge7xgqQJ5IvqlYRRJ] Error Trace: 
- failed to get last migration record (app/pkg/dbx/migrate.go:52)
- dial tcp 10.112.13.58:5432: connect: connection refused
```

Presumably this means fider cannot connect to postgres database but I do not understand why. Is there a way to debug more this? Adding extra logs or something? I have all my pods/services working just fine in the same way. Including a mongo db database.

I have merged my Fider yml files into one here:
https://gist.github.com/javierguzman/47e08b5c54de35ac886cdc530bd702a6

I believe I have all the correct setup and I do not see any typos. 

Any help or hint would be appreciated.

Thank you in advance and regards

**Comment by javierguzman** [comment]
I found the problem, I had a typo in one of the service selectors so that is why data was not routed properly. I updated the gist to reflect this just in case it can help someone in future.

I close the issue.

**Comment by sbkg0002** [comment]
Hey @javierguzman can you share your complete manifest? I'm willing to create a helm chart and create a PR from it.

**Comment by javierguzman** [comment]
Sure @sbkg0002 Happy to do my bit for this project. Give me some days as I am right now away from my normal laptop.

**Comment by javierguzman** [comment]
Hello again @sbkg0002,  I have created the following repository:
https://github.com/javierguzman/kubernetes-fider

In there I have placed the yml templates I use, feel free to grab whatever you need as I am not familiar with the creation of a helm chart.

I run this under a CI/CD environment so some stuff like $VERSION comes from "nowhere/ CI CD"  if you know what I mean. I am not a Kubernetes pro at all so if you find something weird or sensitive data ( I think I removed all) please, let me know!

I hope this helps, regards.
