### ISSUE TITLE
Listen on specific address/interface

### ISSUE THREAD

**Issue by Zauberstuhl** [getfider/fider#903]
Currently fider listens on all addresses/interfaces (https://github.com/getfider/fider/blob/master/app/cmd/server.go#L46). It would be nice if we could configure the listen interface via e.g. a environment variable too.

**Comment by goenning** [comment]
Hey. @Zauberstuhl what’s the use case?

**Comment by Zauberstuhl** [comment]
@goenning I have multiple interfaces and only want to expose it on the internal network.

**Comment by goenning** [comment]
That should be possible on Docker https://docs.docker.com/config/containers/container-networking/

**Comment by Zauberstuhl** [comment]
No, because I am not using docker. If this is something you don't want to support you can close this ticket.
I am already working around this. I just thought it would be nice to have.

Best, Lukas
