### ISSUE TITLE
Backup procedure question

### ISSUE THREAD

**Issue by mikedawson** [getfider/fider#906]
Hi,

I checked the manual ( https://getfider.com/docs/ ) to see if there is a recommended backup procedure, and I couldn't see an exact answer. I noticed that there is a pull request that references this ( https://github.com/getfider/fider/pull/758 ), but that seems to be more about export to CSV (and I can't see anything in that admin area that is about importing the CSV data).

It seems like docker image does not use a data volume. Does this mean that all that needs backed up is the docker-compose settings and the postgresql database? Then the restore procedure would be to use docker-compose again with the same database? Perhaps this is something that should be noted in the documentation? We want to be sure we have backed up the valuable suggestions of our users :)

Thanks,

-Mike

**Comment by mipapo** [comment]
> Does this mean that all that needs backed up is the docker-compose settings and the postgresql database?
By default you just need to backup the database as everything including uploaded images (from posts, page image etc) are uploaded as blobs to the database and the docker compose settings. 

Just if you use "legal pages" like mentioned here: https://getfider.com/docs/how-to-show-legal-pages/  - These files would need a 
backup.

By the way: If you don't want to store images in the databse you could configure an S3 storage or filesystem mount on the docker container:

https://github.com/getfider/fider/blob/b889ae5e7637a28c1c4c71f19fccc05499d6633c/app/pkg/env/env.go#L77

(Not sure if it's possible to migrate the data from database to the object storage).

**Comment by goenning** [comment]
Exactly what @mipapo mentioned :+1: 

I'm moving this to getfider.com to get it covered on docs getfider/getfider.com/issues/17
