### ISSUE TITLE
Incomplete docs (Hosting an instance on Heroku)

### ISSUE THREAD

**Issue by moevbiz** [getfider/fider#908]
I've had a hard time figuring out how to set up Fider on a Heroku instance, because the docs fail to mention the required environment variable `HOST_DOMAIN`.

See: https://github.com/getfider/fider/issues/907

Otherwise: been playing around with Fider a bit. Great application, highly appreciated! thank you! ❤️

**Comment by MattyAyOh** [comment]
i just set it up the other day (still having issues with authentication, but that's a separate issue)

HOST_DOMAIN needs to be set to your Heroku url:
``myapp.herokuapp.com```

**Comment by goenning** [comment]
@MattyAyOh good finding, do you want to submit a PR to https://github.com/getfider/getfider.com ?

**Comment by MattyAyOh** [comment]
docs were updated by commit: 1564d342a84ad7fd2ef8ec70a79458bbb523e8a4

**Comment by MattyAyOh** [comment]
docs were updated by commit: https://github.com/getfider/getfider.com/commit/1564d342a84ad7fd2ef8ec70a79458bbb523e8a4
