### ISSUE TITLE
Problem with Mail Subject Encoding

### ISSUE THREAD

**Issue by mipapo** [getfider/fider#909]
Just took a look at @s3cur3 x-plane fider instance and saw that there is a problem with the encoding in the Mail if special characters are in the name of the fider instance

"Sign in to X-Plane Feature Requests &amp; Suggestions"

**Comment by goenning** [comment]
Is this related to https://github.com/getfider/fider/issues/844?

**Comment by mipapo** [comment]
Yep, sorry for the duplicate.
