### ISSUE TITLE
The getfider.com display as broken when third-party sources blocked

### ISSUE THREAD

**Issue by Aikatsui** [getfider/fider#910]
Can you please remove them from https://getfider.com/? it seems to me really not necessary

![image](https://user-images.githubusercontent.com/63988538/110065802-9bfaa200-7da2-11eb-8c84-997f7957a0bb.png)

**Comment by mipapo** [comment]
The correct repository would be https://github.com/getfider/getfider.com/issues
Please open the ticket there

**Comment by Aikatsui** [comment]
@mipapo forgot, it came to mind after opened issue. moved to https://github.com/getfider/getfider.com/issues/15
