### ISSUE TITLE
Heroku Deploy Failed: Push rejected, failed to compile Go app.

### ISSUE THREAD

**Issue by mikepsinn** [getfider/fider#914]
I believe I followed the instructions at [https://getfider.com/docs/hosting-on-heroku](https://getfider.com/docs/hosting-on-heroku) perfectly, but initial deploy logs are:
```
-----> Building on the Heroku-20 stack
-----> Go app detected
-----> Fetching jq... done
-----> Fetching stdlib.sh.v8... done
-----> 
       Detected go modules via go.mod
-----> 
       Detected Module Name: github.com/getfider/fider
-----> 
 !!    The go.mod file for this project does not specify a Go version
 !!    
 !!    Defaulting to go1.12.17
 !!    
 !!    For more details see: https://devcenter.heroku.com/articles/go-apps-with-modules#build-configuration
 !!    
-----> New Go Version, clearing old cache
-----> Installing go1.12.17
-----> Fetching go1.12.17.linux-amd64.tar.gz... done
-----> Determining packages to install
 !     Push rejected, failed to compile Go app.
 !     Push failed
```

It's pretty cryptic, but I wonder if anyone else experienced this and resolved it? Thanks!

![image](https://user-images.githubusercontent.com/2808553/110824128-62211400-8258-11eb-8841-0848c45de8c6.png)

**Comment by goenning** [comment]
I don’t use Heroku and the log doesn’t help, but there’s a chance it’s failing because it’s using Go 1.12 instead of 1.16

**Comment by mikepsinn** [comment]
Thanks, @goenning !

**Comment by goenning** [comment]
@mikepsinn should work fine now, can you please try again?
