### ISSUE TITLE
Host Header Injection Critical Security Vulnerability

### ISSUE THREAD

**Issue by omemishra** [getfider/fider#915]
Dear Team,

Hope you are doing well, i have hosted your application and find one vulnerability.

host header injection in which attacker can poison the password reset token and can takeover the users account.

Steps:-

1. Goto forget password page 
2. Intercept the request in burp
3. Chnage the host to evil.com
4. You will revieve a password reset token of evil.com/token

Reference:-
https://www.netsparker.com/web-vulnerability-scanner/vulnerabilities/http-header-injection/
![HHI](https://user-images.githubusercontent.com/25466820/110841501-f6788e80-82cb-11eb-8247-edda5ba1d98f.png)
![HHI-email](https://user-images.githubusercontent.com/25466820/110841509-f8425200-82cb-11eb-915c-dd219f187e9b.png)

Thanks & Regards
Ome

**Comment by goenning** [comment]
Hi @omemishra what version are you using?

**Comment by omemishra** [comment]
Dear Getfider/Fider Team,


I am using the latest version.

**Comment by goenning** [comment]
When you say latest version, is the stable or master tag?

**Comment by goenning** [comment]
I’m asking because it was fixed here https://github.com/getfider/fider/pull/895/files , but it’s not yet on the stable tag
