### ISSUE TITLE
Help with docker / postgres connection

### ISSUE THREAD

**Issue by spencerflagg** [getfider/fider#922]
I have both Fider and Postgres running in docker containers, and am getting `dial tcp 0.0.0.0:5432: connect: connection refused` in the logs.

I'm sure that I need to change something about the Postgres config, but I've been spinning my wheels so far.

If someone has any lessons learned, or could post their Postgres and/or Fider _docker-compose.yml_, I'd be eternally grateful.

**Comment by goenning** [comment]
have you linked those two containers?

our previous docs used to have docker and postgres in a docker-compose: https://github.com/getfider/getfider.com/blob/f4c5e89ec35892bd6f6ff05c7bb44ab7061dfed9/content/docs/hosting-instance.md

**Comment by spencerflagg** [comment]
Thanks for that! No, I hadn't linked the containers, and your example helped immensely.
I'm new to Docker, so I'm still piecing all of this together. When all is said and done I'll post my lessons learned for posterity.

Now I've got both Fider and Postgres running with no errors, and can hit the login page. 🥳 

One more question - I can move it elsewhere if necessary....
Is there any documentation on how to get Fider with SSL hosted via Caddy?
