### ISSUE TITLE
Callback URL results in HTTP 500

### ISSUE THREAD

**Issue by robd518** [getfider/fider#929]
I'm using the Dockerized version of Fider.  I set up a custom OAuth provider to Keycloak for LDAP.  I have confirmed that Keycloak works properly to return the profile of the user upon successful login.  I've set up a client in Keycloak for Fider.

When I go to Fider, click my custom LDAP login button, I'm taken to Keycloak to sign in.  I see the successful login event in Keycloak.  What happens next has me confused.  My browser will spin for a bit, then time out with an HTTP 500.  More specifically, it will say:

```
The webpage at https://<fiderurl>/oauth/_<stub>/echo?code=<code>?identifier=<code> might be temporarily down or it may have moved permanently to a new web address

ERR_HTTP2_PROTOCOL_ERROR
```  

Has anyone else experienced this?

**Comment by goenning** [comment]
does it happen to any other custom oauth or just when using keycloak?

**Comment by robd518** [comment]
Hi there - I was just coming here to say that I stood this up in my own personal environment without SSL and without a proxy and it works flawlessly.  I discovered that the reason I was getting the error message above was because of a combination of a proxy and SSL certificate error.  I will open up a request to ask for an environment variable to ignore SSL errors. 

Apologies for wasting time.
