### ISSUE TITLE
New release version @ docker hub

### ISSUE THREAD

**Issue by gs11** [getfider/fider#933]
Thanks again for an excellent piece of software!

I've so far been using my own docker image to get the changes included in https://github.com/getfider/fider/pull/926
I noted that the latest semver versioned tag on docker hub is fairly old.

Would you consider creating a new tag and version that could be available at docker hub as well?

**Comment by goenning** [comment]
Yes, I’ll release a 0.18.1 soon, hopefully this weekend

**Comment by goenning** [comment]
https://getfider.com/blog/version-0.18.1

**Comment by gs11** [comment]
Thank you very much! @goenning
