### ISSUE TITLE
Error Running 201904022134_lowercase_emails.sql Migration

### ISSUE THREAD

**Issue by jimmybrancaccio** [getfider/fider#935]
I'm using Fider in a Docker environment and it looks like it's caught up on running the `201904022134_lowercase_emails.sql` migration.

```
INFO [2021-03-28T09:58:23-05:00] [MIGRATE] [bTDMZoJGxQOuu5UVuAPXO7BvkAmUg1Jx] Running migrations...,
INFO [2021-03-28T09:58:23-05:00] [MIGRATE] [bTDMZoJGxQOuu5UVuAPXO7BvkAmUg1Jx] Found total of 63 migration files.,
INFO [2021-03-28T09:58:23-05:00] [MIGRATE] [bTDMZoJGxQOuu5UVuAPXO7BvkAmUg1Jx] Current version is 201901130830,
INFO [2021-03-28T09:58:23-05:00] [MIGRATE] [bTDMZoJGxQOuu5UVuAPXO7BvkAmUg1Jx] Running Version: 201904022134 (201904022134_lowercase_emails.sql),
ERROR [2021-03-28T09:58:23-05:00] [MIGRATE] [bTDMZoJGxQOuu5UVuAPXO7BvkAmUg1Jx] Error Trace: ,
- failed to run migration '201904022134_lowercase_emails.sql' (app/pkg/dbx/migrate.go:77),
- pq: duplicate key value violates unique constraint "user_email_unique_idx"
```

Running the query manually I get:

```
Query 1 ERROR: ERROR:  duplicate key value violates unique constraint "user_email_unique_idx"
DETAIL:  Key (tenant_id, email)=(1, co*****.ro****@googlemail.com) already exists.
```

However running:

```sql
SELECT * FROM users WHERE email='co*****.ro****@googlemail.com';
```

returns only a single result. I'm not well versed with PostgreSQL, but the error doesn't make sense to me since only a single result is returned.

I'm using the latest Docker image with PostgreSQL 12.

**Comment by goenning** [comment]
Try this `SELECT * FROM users WHERE lower(email)='co*****.ro****@googlemail.com';`

you might have two users with the same email

**Comment by jimmybrancaccio** [comment]
@goenning Ah yup, that was it, didn't realize it was case sensitive. I just manually edited one of the emails to something else. Odd that snuck in but it could have happened before my duplicate email checking code was implemented on my site.

**Comment by tziemek** [comment]
Is this documented somewhere? Ran into the same behavior and had to cleanup my database manually.
