### ISSUE TITLE
How to import database?

### ISSUE THREAD

**Issue by itsnotsaved** [getfider/fider#956]
I exported fider database from web and deployed heroku instance https://getfider.com/docs/hosting-on-heroku
i dont know how to import database to its postgress. @goenning how to do that?

uptimerobot no longer support for custom domains under free plan https://status.fider.io/
i found another free alternative https://betteruptime.com may be you can find something else better.

https://hetrixtools.com/uptime-monitor
https://www.statuspage.so
https://www.squadcast.com
https://upptime.js.org/

**Comment by goenning** [comment]
There's no official process to import, but there's a community script that might help you https://gist.github.com/m3nu/1228a25b883ae8c49de471d0c8d37b90

**Comment by itsnotsaved** [comment]
> There's no official process to import, but there's a community script that might help you https://gist.github.com/m3nu/1228a25b883ae8c49de471d0c8d37b90

I dont have good idea how to do that because i'm using heroku deployment https://getfider.com/docs/hosting-on-heroku
