### ISSUE TITLE
Cannot run SSL Termination on reverse proxy on different port

### ISSUE THREAD

**Issue by GraemeMitchell84** [getfider/fider#960]
I'm trying to run Fider behind an nginx proxy which is handling the SSL termination.  The variance in my scenario is that I'm listening on a none standard port in Nginx which is 10016 in my case.  Nginx then manages the SSL and routes this request to Fider on port 3000 sending the appropriate x-forwarded headers. I'm able to make the initial request to Fider, but the page fails to load fully.  I see that my initial GET for the page was successful, but the links within the HTML response reference addresses at HTTPS on port 443 (no port specified) rather than the port I used.  For example: -

`https://mydomain.com/assets/js/runtime.2ad0160f15a50d15422c.js`

instead of: -

`https://mydomain.com:10016/assets/js/runtime.2ad0160f15a50d15422c.js`

Here is my nginx config for reference: -
 
```
upstream fider {

    server fider-app-1:3000;
}

server {

    listen 10016 http2 ssl;
    listen  [::]:10016 http2 ssl;
    server_name  mydomain.com;

    ssl_certificate /some/cert.crt;
    ssl_certificate_key /some/key.key;
    ssl_dhparam /some/dhparam/dhparam.pem;
    ssl_protocols TLSv1.2;

    location / {

        proxy_pass http://fider;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}
```

**Comment by mipapo** [comment]
Do you have correctly set HOST_DOMAIN to https://mydomain.com?

**Comment by goenning** [comment]
hey @GraemeMitchell84 can you have a look at  this PR #1069

If you're still having this issue, please try using `getfider/fider:PR_1069` this version of the image contains this change.

**Comment by goenning** [comment]
I'm going to close this one as the latest version greatly simplify this by using relative path to resources. Just remember to set `BASE_URL` instead of `HOST_DOMAIN`.
