### ISSUE TITLE
Delete declined/duplicate/completed posts from the database

### ISSUE THREAD

**Issue by masteradit** [getfider/fider#961]
Is there any option to delete declined/duplicate/completed posts from the database?

I recently noticed that the database fills up really quickly with every post. Just 2 new posts added around 600 new rows in the Heroku PostgreSQL database (number of rows went from 4588 to 5192). The free limit is 10k rows. Thus, I think this feature can be really useful.

**Comment by masteradit** [comment]
I checked the number of rows in each table and saw that the "logs" table has the most amount of rows. Can I drop the logs table? Would it cause any issues with Fider?

**Comment by goenning** [comment]
You can't drop it, but you can set the LOG_LEVEL environment variable to ERROR to reduce the noise
