### ISSUE TITLE
[BUG] Fider "PAGE NOT FOUND" after email activation

### ISSUE THREAD

**Issue by taewookim** [getfider/fider#987]
**Fider Cloud or Self Hosted**
OS: Ubuntu 20.04 LTS w/nginx as proxy
Self hosted  / docker with docker-compose.yml from [docs](https://getfider.com/docs/hosting-instance)

**Describe the bug**
Deploy using docker-dompose
1) complete /signup
2) Receive email. Click on activation link

Page (/signup/verify?k=...) shows "PAGE NOT FOUND" html. When I go to the fider home page (i.e. HOST_DOMAIN), now the page shows "PAGE NOT FOUND" as well.

For some reason, setting HOST_DOMAIN to localhost:<some port> does not address this issue, which made me wonder if this was nginx config issue (I was using [this nginx config](https://github.com/getfider/fider/issues/846#issuecomment-614295287))

However, when I "curl http://localhost:<port_num>", i can see that the returned HTML is the same with clear reference to https://getfider.com/images/logo-100x100.png

**Comment by asos-robbell** [comment]
Why was this bug closed? I'm experiencing the same thing in my Kubernetes deployment of Fider. After I set the Fider instance description and the activation link is sent the application falls into a CrashLoop. Looking at logs on the application pod I can see that connections to Fider are still being logged but it's returning 404s:

```
INFO [2022-02-04T15:13:10Z] [WEB] GET http://10.0.0.33:3000/ started
INFO [2022-02-04T15:13:10Z] [WEB] GET http://10.0.0.33:3000/ finished with 404 in 6ms (committed)
```

**Comment by rafaelbantu** [comment]
I had this problem and only solved it after setting a URL. With IP did not work.
