### ISSUE TITLE
[BUG] failed to send email with template signup_email

### ISSUE THREAD

**Issue by rodrigo-brito** [getfider/fider#995]
**Fider Cloud or Self Hosted**
0.19.0

**Describe the bug**
I have a similar issue to https://github.com/getfider/fider/issues/943

But, In my case, the problem occurs with the TLS Domain. In the current version, the TLS domain is extracted from the server domain: https://github.com/getfider/fider/blob/main/app/services/email/smtp/smtp.go#L101-L116

But, in some cases, we can use a different domain for server address and TLS address.

For example:
- SMTP server is accessible only in the internal network (such as the Kubernetes cluster).
- TLS uses a certificate signed by another domain (different from the internal DNS address)

**Comment by goenning** [comment]
Is that a common setup? 

I'd imagine in most cases the smtp server would have a private dns and the certificate would be signed for the same name?

**Comment by rodrigo-brito** [comment]
No, It is a very specific case. No problem, I will close the PR.

**Comment by javierguzman** [comment]
Hello @goenning  and @rodrigo-brito I am getting this error after upgrading from 0.18 to 0.21, is there something I need to change? It has been working ok before upgrading.

There is a error trace which at the ends says:
```
- github.com/getfider/fider/app/services/email/smtp.sendMail:105 (app/pkg/errors/errors.go:39)
- failed to send email with template signin_email (app/services/email/smtp/smtp.go:105)
- 501 Syntax: HELO hostname
```

Thank you in advance and regards

**Comment by rodrigo-brito** [comment]
From internal network without TLS it's impossible to use.

**Comment by lcfd** [comment]
👋🏼  Hi

We are experiencing the same error using port 465 and EMAIL_SMTP_ENABLE_STARTTLS="false".
Fider is installed using Docker and exposed via Traefik.


The error in the console:
```
- github.com/getfider/fider/app/services/email/smtp.sendMail:105 (app/pkg/errors/errors.go:39)
- failed to send email with template signup_email (app/services/email/smtp/smtp.go:105)
- dial tcp xxx.xxx.xxx.xxx:465: connect: connection timed out

INFO [] [BGW] Task 'Send sign up email' finished in 129860ms (panicked)
```
